<?php
namespace App;

use App\Helpers\Paths;

class VendorData
{

    /**
     * Unique object instance.
     *
     * @var VendorData
     */
    private static $instance;

    public $vendorTable;

    /**
     * Return the unique plugin instance.
     *
     * @return VendorData
     */
    public static function getInstance()
    {
        if (null === self::$instance) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    protected function __construct()
    {
        $this->vendorTable = self::reindexVendorData(self::getVendorCsvData());
    }

    public static function getVendorCsvData()
    {
      // Retrieve the list of vendors from the goc-spending-vendors repository folder
        $filepath = Paths::getVendorDataDirectory() . "vendor_data.csv";
        $vendorData = [];

        if (file_exists($filepath)) {
           // Thanks to
           // http://php.net/manual/en/function.str-getcsv.php#117692
            $csv = array_map('str_getcsv', file($filepath));
            array_walk($csv, function (&$a) use ($csv) {
                $a = array_combine($csv[0], $a);
            });
            array_shift($csv);
        } else {
            echo "Error: could not load vendor_data.csv file. Make sure the goc-spending-vendors repository exists. \n";
        }

      // Re-index according to the usual structure (parent => childArray)
        if (is_array($csv)) {
            foreach ($csv as $row) {
              // dd($row);
                if ($row['Company name']) {
                    $vendorData[$row['Parent company']][] = $row['Company name'];
                }
            }
        } else {
            echo "Error: could not parse the vendor_data.csv file. Make sure that vendor_data.csv is a valid CSV file. \n";
        }
      
        return $vendorData;
    }

    // Re-index the vendor data so that the name variants are keys and the common name is the value for each, to speed up matching in the consolidateVendorNames function:
    public static function reindexVendorData($vendors)
    {

        $vendorTable = [];

        foreach ($vendors as $vendor => $vendorNames) {
            foreach ($vendorNames as $vendorName) {
                $vendorTable[self::cleanupVendorName($vendorName)] = self::cleanupVendorName($vendor);
            }
        }

        return $vendorTable;
    }

    public function consolidateVendorNames($vendorName)
    {

        $vendorName = self::cleanupVendorName($vendorName);

        $output = $vendorName;

        if (isset($this->vendorTable[$vendorName])) {
            $output = $this->vendorTable[$vendorName];
        }

        // if($vendorName != $output) {
        //  echo "Replacing [$vendorName] with [$output]. \n";
        // }

        return $output;
    }

    public static function cleanupVendorName($input)
    {

        $charactersToRemove = [
            ',',
            "'",
            "\t",
            '.',
            ' INCORPORATED',
            ' INC',
            ' LTD',
            ' -',
            ' /',
            '/ ',
            ' LIMITED',
            ' LIMITE',
            ' LCC',
            ' LLC',
            '"',
            ')',
            '(',
            '#',
            ':',
            ' \\',
            '\\ ',
        ];

        $output = str_replace($charactersToRemove, ' ', strtoupper($input));

         // 2nd pass
        $output = str_replace($charactersToRemove, ' ', strtoupper($input));

         // Remove extra spaces
        $output = str_replace(['    ', '   ', '  '], ' ', $output);

        $trimCharacters = [
         '-',
         '&',
         '/',
         '\\',
         '*',
         '@',
        ];

        foreach ($trimCharacters as $character) {
            $output = trim($output, $character);
        }

        return trim($output);
    }

    public static $vendors = [

        'IBM CANADA' => [
            'IBM',
            'IBM Business Consulting Services',
            'IBM BUSINESS CONSULTING SERVICES/',
            'IBM CAN*91898807',
            'IBM CANADA',
            'IBM CANADA LIMITED',
            'IBM CANADA LTD',
            'IBM CANADA LTD.',
            'IBM CANADA LTEE',

            '2026695 IBM CANADA',
            'DONNA CONA IBM CANADA IN',
            'DONNA CONA IBM CANADA IN JOINT VENTURE',
            'DONNA CONA IBM CANADA LIMITED IN JOINT VENTURE',
            'GROUPE LGS-IBM',
            'IBM BELGIUM NV SV PLI-GLOBAL',
            'IBM BUSINESS CONSULTING SERVICES M',
            'IBM CANADA 16TH FLOOR',
            'IBM CANADA 16TH FLOOR SUITE 1610',
            'IBM CANADA ATTN: KAREN CRAWFORD',
            'IBM CANADA LIMITED 102444452PG0014',
            'IBM CANADA LIMITED/IBM CANADA LIMITA?E',
            'IBM CANADA LIMITED/IBM CANADA LIMITIE',
            'IBM CANADA LTA(C)E',
            'IBM CANADA M2108',
            'IBM CANADA (MARKHAM)',
            'IBM CANADA MARKHAM ON',
            'IBM CANADA OTTAWA',
            'IBM CANADA T-5044',
            'IBM CDA',
            'IBM CNADA LIMITED',
            'IBM CORPORATION',
            'IBM GLOBAL BUSINESS SERVICES',
            'IBM GLOBAL SERVICES',
            'IBM GLOBAL TECHNOLOGY SERVICES',
            'IBM SECURITY SOLUTIONS LEADER',
            'IBM SOFTWARE CONSOLIDATION',
            'SPSS AN IBM COMPANY',

            'IBM COGNOS',
            'COGNOS USER CONFERENCE',
            'COGNOS ULC',
            'COGNOS',

        ],

        'BELL CANADA' => [
            'THE BELL TELEPHONE COMPANY OF',
            'THE BELL TELEPHONE COMPANY OF CANADA',
            'The Bell Telephone Company of Canada  / Bell Canada',
            'Bell',
            'Bell Advanced Communications',
            'BELL ALIANT',
            'BELL ALIANT REGIONAL',
            'BELL ALIANT REGIONAL COMM.    L.P',
            'BELL ALIANT REGIONAL COMM.   L.P',
            'BELL ALIANT REGIONAL COMM. L.P',
            'BELL ALIANT REGIONAL COMMUNICATIONS',
            'Bell Aliant Regional Communications L.P',
            'Bell Aliant Regional Communications L.P.',
            'Bell Aliant Regional Communications, LP',
            'BELL CANADA',
            'Bell Canada ICT Solutions',
            'Bell Canada, Enterprise Division',
            'BELL MOBILITY',
            'Bell Mobility Inc.',
            'BELL NEXXIA',
            'BELL WORLD/KANATA WRLSS',
            'BELL/BCE NEXXIA Inc.',

            'BELL ALIANT (HALIFAX)',
            'BELL ALIANT REGIONAL COMM PARTN',
            'BELL ALIANT REGIONAL COMMUNICA',
            'BELL ALIANT REGIONAL COMMUNICATIONS/BELL ALIANT COMMUNICATIONS RE',
            'BELL ALIANT REGIONAL COMMUNICATIONS LIMITED PARTNERSHIP',
            'BELL ALIANT REGIONAL COMMUNICATIONS LIMUITED PARTNERSHIP',
            'BELL ALLIANT',
            'BELL ALLIANT REGIONAL',
            'BELL ALLIANT REGIONAL COMMUNICATIONS LIMITED',

            'BELL CANADA 8713',
            'BELL CANADA & ADVANCED EDUCATION CORPORATION',
            'BELL CANADA AND BELL SECURITY SOLUTIONS IN JOINT VENTURE',
            'BELL CANADA [AUTHORIZED HP RESELLER]',
            'BELL CANADA/BELL NEXXIA',
            'BELL CANADA/BELL WEB SOLUTIONS',
            'BELL CANADA CENTRE DE VERSEMENTS CLIENTS',
            'BELL CANADA COMPANY',
            'BELL CANADA C/O SPECIAL BILLING',
            'BELL CANADA CUSTOMER COMMUNICATIONS CTR',
            'BELL CANADA ENTERPRISE GROUP',
            'BELL CANADA (MISSISSAUGA)',
            // 'BELL CANADA MTS ALLSTREAM TELUS COMMUNICATIONS COMPANY BELL ALIANT REGIONAL COMMUNICATIONS (LIMITED PARTNERSHIP) SASKATCHEWAN TELECOMMUNICATIONS',
            'BELL CANADA (OTTAWA)',
            'BELL CANADA/THE BELL TELEPHONE',
            'BELL CDA',
            'BELL CDA SECURITY SOLUTIONS',

            'BELL EXPRESSU LIMITED PARTNERSHIP',
            'BELL EXPRESSVU PARTNERSHIP',
            'BELL GEOSPACE ENTERPRISES',
            'BELL GLOBAL SOLUTIONS',
            'BELL GLOBEMEDIA PUBLISHING',
            'BELL GLOBEMEDIA PUBLISHING/PUBLICATIONS',

            'BELL ICT SOLUTIONS',

            'BELL MEDIA',
            'BELL MOBILITE',
            'BELL MOBILITE RADIO',
            'BELL MOBILITY CANADA',
            'BELL MOBILITY CENTER',
            'BELL MOBILITY PAGING',
            'BELL MOBILITY RADIO',
            'BELL MOBILITY (RADIO DIVISION)',
            'BELL MOBILITY RADIO DIVISION',

            'BELL-NEXXIA',
            'BELL NEXXIA (OTTAWA)',

            'BELL SECURITY SOLUTIONS',
            'BELL SECURITY SOLUTIONS (BSS',
            'BELL SECUTITY SOLUTIONS',

            'BELLTECH SYSTEM',
            'BELL TECH SYSTEMS',
            'BELL TELEPHONE COMPANY OF CANADA',
            'BELL WHOLESALE',
            'BELL WIRELESS ALLIANCE',

            'THE BELL TELEPHONE COMPANY OF CANAD',
            'THE BELL TELEPHONE COMPANY OF CANADA OR BELL',
            'THE BELL TELEPHONE COMPANY OF CANADA OR BELL CANADA',
            'THE BELL TELEPHONE COMPANY OF CANADA OR BELL CANADA/LA COMPAGNIE DE TA?',
            'THE BELL TELEPHONE COMPANY OF CANADA OR BELL CANADA/LA COMPAGNIE DE TA(C)',
            'THE BELL TELEPHONE COMPANY OF CANADA OR BELL CANADA/LA COMPAGNIE DE TA(C)LA(C)PHONE BELL DU CANADA OU BELL CANADA',
            'THE BELL TELEPHONE COMPANY OF CANADA OR BELL CANADA\LA COMPAGNIE DE TA(C)LA(C)PHONE BELL DU CANADA OU BELL CANADA',
            'THE BELL TELEPHONE COMPANY OF CANADA OR BELL CANADA/LA COMPAGNIE DE TE',
            'THE BELL TELEPHONE COMPANY OF CANADA OR BELL CANADA/LA COMPAGNIE DE TI',

            'XWAVE A DIVISION OF BELL ALIANT',
            'XWAVE-A DIVISION OF BELL ALIANT',
            'XWAVE A DIVISION OF BELL ALIANT REG',
            '"XWAVE A DIVISION OF BELL ALIANT REGIONAL COMMUNICATIONS       "',
            'XWAVE A DIVISION OF BELL ALIANT REGIONAL COMMUNICATIONS',
            'XWAVE A DIVISION OF BELL ALLIANT',

            'BELL CONFERENCING',

        ],

        'MICROSOFT CANADA' => [

            'Microsoft',
            'Microsoft Canada',
            'MICROSOFT CANADA CO.',
            'MICROSOFT CANADA INC',
            'MICROSOFT CANADA INC.',
            'MICROSOFT CANADA LTD.',
            'MICROSOFT CORPORATION',
            'MICROSOFT LICENCING , GP',
            'Microsoft Licensing GP',
            'MICROSOFT LICENSING, GP',

            'MICROSOFT CANADA ATT: PAT BRISCOE',
            'MICROSOFT CANADA COMPANY',
            'MICROSOFT CANADA CO(MSLIGP)',
            'MICROSOFT CANADA MISSISSAUGA',
            'MICROSOFT CANADA (OTTAWA)',
            'MICROSOFT CONSULTING SERVICES',
            'MICROSOFT CONSULTING SERVICES (MCS)',
            'MICROSOFT CORP',
            'MICROSOFT CORPOARATION',
            'MICROSOFT CORPOARATION: WRC-CA',
            'MICROSOFT CORPORATION ONE MICROSOFT WAY SAMM-D',
            'MICROSOFT CORPORATION REDMOND USA',
            'MICROSOFT CORPORATION REDMOND WA USA',
            'MICROSOFT ENTREPRISE AGREEMENT',
            'MICROSOFT LICENCING GP',
            'MICROSOFT LICENSES SOFTWARE HOUSE INTERNATIONAL',
            'MICROSOFT LICENSING',
            '"""MICROSOFT LICENSING GP"""',
            'MICROSOFT LICENSING GP (MSLI GP)',
            'MICROSOFT LICENSING GP WRC-CA',
            'MICROSOFT LICENSING GROUP',
            'MICROSOFT SERVICES',
            'MICROSOFT TECHNOLOGIES',
            'MSLI MICROSOFT LICENSING GP',


        ],

        'HEWLETT PACKARD' => [

            'Hewlett Packard (Canada)',
            'HEWLETT PACKARD (CANADA) CO.',
            'Hewlett Packard (Canada) Ltd',
            'HEWLETT PACKARD CANADA',
            'HEWLETT PACKARD CANADA CO.',
            'Hewlett-Packard (Canada)',
            'HEWLETT-PACKARD (CANADA) CO',
            'HEWLETT-PACKARD (CANADA) CO.',
            'HEWLETT-PACKARD (CANADA) LTD',
            'Hewlett-Packard (Canada) Ltd.',
            'HEWLETT-PACKARD CANADA',
            'Hewlett-Packard Canada Ltd',
            'HEWLETT-PACKARD CANADA LTD.',
            'Hewlett-Packard Ltd.',
            'HewlettPackard (Canada) Co.',
            'HP Canada Co.',

            'AUTONOMY:  AN HP COMPANY',
            'AUTONOMY: AN HP COMPANY',
            'AUTONOMY HP',
            'HP AUTONOMY',
            'HP CANADA',
            'HP CANANDA CO',
            'HP CORP',
            'HPE',
            'HP ENTERPRISE (CANADA) CO',
            'HP ENTERPRISE SERVICES LLC',
            'HP METAFORE',
            'HP/ METAFORE',
            'HP METAFORE TECHNOLOGIES',
            'HP RESELLER: MICROAGE',
            'METAFORE (RESELLER HP CANADA)',
            'XWAVE (CARE OF HP)',

            'HEWLETT MINPACO',
            'HEWLETT PACKARD',
            'HEWLETT-PACKARD (CA) CO',
            'HEWLETT PACKARD (CANADA )',
            'HEWLETT PACKARD (CANADA]',
            'HEWLETT- PACKARD (CANADA)',
            'HEWLETT-PACKARD (CANADA]',
            'HEWLETT-PACKARD (CANADA)CO',
            'HEWLETT-PACKARD (CANADA] CO',
            'HEWLETT-PACKARD CANADA CO',
            'HEWLETT-PACKARD(CANADA)CO',
            'HEWLETT-PACKARD (CANADA) COBLOCK',
            'HEWLETT-PACKARD CANADA CO C/O MICROAGE',
            'HEWLETT-PACKARD CANADA CO C/O ZYCOM',
            'HEWLETT PACKARD (CANADA) C/O FOXWISE TECHNOLOGIES',
            'HEWLETT-PACKARD (CANADA) CO H',
            'HEWLETT-PACKARD ( CANADA ) CO HEWLETT-PACKARD ( CANADA ) CIE',
            'HEWLETT-PACKARD (CANADA) CO HEWLETT-PACKARD (CANADA) CIE',
            'HEWLETT-PACKARD (CANADA) COMPANY',
            'HEWLETT PACKARD (CANADA) LT',
            'HEWLETT PACKARD CANADA ( RESELLER- CLICK-INTO)',
            'HEWLETT PACKARD C/O MICROAGE',
            'HEWLETT PACKARD COMPANY',
            'HEWLETT-PACKARD C/O ZYCOM',
            'HEWLETT PACKARD ENTERPRISE',
            'HEWLETT PACKARD ENTERPRISE CANADA',
            'HEWLETT PACKARD ENTERPRISE CANADA C',
            'HEWLETT PACKARD ENTERPRISE CANADA CO',
            'HEWLETT PACKARD ENTREPRISE',
            'HEWLETT-PACKARD FINANCIAL SERVICES',
            'HEWLETT PACKARD METAFORE',
            'HEWLETT PACKARD RESELLER: IMP SOLUTIONS',
            'HEWLETT-PACKARD STATION J',
            'HEWLETT PARCKARD',
            'HYPERTEC (HEWLETT PACKARD RESELLER)',
            'HYPERTEC SYSTEMS (HEWLETT PACKARD RESELLER)',
            'ITEX(HEWLETT PACKARD)',
            'RVD HEWLETT PACKARD',
            'EDS(HP) CANADA',

        ],

        'CGI' => [

            'CGI INFORMATION SYSTEMS',
            'CGI INFORMATION SYSTEMS &',
            'CGI Information Systems & Management Consultants',
            'CGI Information Systems & Management Consultants I',
            'CGI Information Systems & Management Consultants Inc.',
            'CGI INFORMATION SYSTEMS AND',
            'CGI Information Systems and Management Consultant',
            'CGI Information Systems and Management Consultants',
            'CGI INFORMATION SYSTEMS AND MANAGEMENT CONSULTANTS INC',
            'CGI INFORMATION SYSTEMS AND MANAGEMENT CONSULTANTS INC.',
            'CGI INFORMATION SYSTMES AND',
            'CGI Payroll Services Centre',
            'CGI/AMS MANAGEMENT SYSTEMS',
            'CGI INFORMATIONS SYSTEMS AND MANAGEMENTS CONSULTANTS',

            'CGI GROUP',
            'CGI GROUP (THE)',
            'CGI INFORMATION',
            'CGI INFORMATIONS SYSTEMS',
            'CGI INFORMATIONS SYSTEMS AND MANAGEMENT CONSULTANTS',
            'CGI INFORMATIONS SYSTEMS AND MANAGEMENT CONSULTING',
            'CGI  INFORMATIONS SYSTEMS AND MANAGEMENTS CONSULTANTS',
            'CGI INFORMATION SYSTEM',
            'CGI INFORMATION SYSTEM AND MANAGEMENT',
            '* CGI INFORMATION SYSTEMS &',
            'CGI INFORMATION SYSTEMS AND MA',
            'CGI INFORMATION SYSTEMS AND MANAGEM',
            'CGI INFORMATION SYSTEMS AND MANAGEMENT',
            'CGI INFORMATION SYSTEMS AND MANAGEMENT CONSU',
            'CGI INFORMATION SYSTEMS AND MANAGEMENT CONSULTANTS CONSEILLERS EN SYSTA?MES DINFORMATION ET EN GESTION CGI',
            'CGI INFORMATION SYSTEMS AND MANAGEMENT CONSULTATNTS',
            'CGI INFORMATION SYSTEMS AND MANAGEMENT CONSULTING',
            'CGI INFORMATION SYSTEMS AND MANAGMENT',
            'CGI INFORMATION SYSTEMS AND MGMT CONSULTANTS',
            'CGI INFORMATION SYSTEMS AND TECHNOLOGY',
            'CGI INFORMATION SYSTEMS MAN',
            'CGI INFORMATION SYSTEMS & MANAGEMENT',
            'CGI INFORMATION SYSTEMS & MANAGEMENT CONSULTANT',
            'CGI INFORMATION SYSTEMS MANAGEMENT CONSULTANTS',
            'CGI INFORMATION SYTEMS AND MANAGEME',
            'CGI INFO SYSTEMS',
            'CGI INFO SYSTEMS & MANAGEMENT',
            'CGI INFO SYSTEMS & MGMT',
            'CGI IT/NET IN JOINT VENTURE',
            'CGI PAYROLL SERVICES CENTER',
            'CGI PAYROLL SERVICES CENTRE CENTRE DE SERVICES DE PAIE CGI',
            'CGI PAYROLL SERVICES CNTR',

        ],

        'ROGERS' => [

            'Rogers AT&T',
            'ROGERS BUSINESS SOLUTIONS',
            'ROGERS CABLE COMMUNICATIONS INC',
            'ROGERS CABLE INC',
            'Rogers Cable Inc.',
            'Rogers Communications',
            'ROGERS COMMUNICATIONS CANADA INC.',
            'ROGERS COMMUNICATIONS INC.',
            'ROGERS COMMUNICATIONS PARTNERSHIP',
            'ROGERS DATA CENTRES INC.',
            'ROGERS OTTAWA',
            'ROGERS WIRELESS',

            'CELLULAR UNLIMITED/ ROGERS AT & T',
            'CKER FM ROGERS MEDIA',
            'LE GROUPE ROGERS',
            'LE GROUPE ROGERS LTEE',
            'ROGERS AT&T WIRELESS',
            'ROGERS ATT WIRELESS',
            'ROGERS BLUE JAYS BASEBALL',
            'ROGERS BROADCASTING LIMITED/',
            'ROGERS BROADCASTING LIMITED/ROGERS MEDIA',
            'ROGERS CABLE COMMUNICATIONS/COMMUNICATIONS ROGERS CABLE',
            'ROGERS CABLE COMUNICATIONS',
            'ROGERS CABLE SERVICES',
            'ROGERS CABLE SYSTEMS',
            'ROGERS CANTEL',
            'ROGERS COMMUNICATION',
            'ROGERS COMMUNICATION CANADA',
            'ROGERS CONSULTING',
            'ROGERS DATA CENTER',
            'ROGERS DATA CENTRE',
            'ROGERS ENTERPRISES LIMITED',
            'ROGERS MEDIA',
            'ROGERS MEDIA C/O CREATIVE SHOW PRODUCTIONS',
            'ROGERS MEDIA PUBLISHING',
            'ROGERS MEDIA PUBLISHING LIMITED',
            'ROGERS OTTAWA LIMITED',
            'ROGERS PAYMENT CENTER',
            'ROGERS PAYMENT CENTRE',
            'ROGERS PUBLISHING',
            'ROGERS PUBLISHING LIMITED',
            'ROGERS PUBLISHING MAGAZINE',
            'ROGERS SHARED SERV/ROGERS COMMINC',
            'ROGERS TELECOM',
            'ROGERS TELECOM ATT DIANE MENARD ACCOUNT CONSULTANT',
            'ROGER WIRELESS',


        ],
         
         'ORACLE CANADA' => [

            'Oracle',
            'ORACLE CANADA',
            'ORACLE CANADA ULC',
            'Oracle Canada ULC.',
            'ORACLE CORPORATION',
            'ORACLE CORPORATION CANADA INC',
            'ORACLE CORPORATION CANADA INC.',

            'ORACLE  CANADA ULC',
            'ORACLE CANADA ULC OTTAWA ON',
            'ORACLE CORP',
            'ORACLE CORP CANADA',
            'ORACLE CORPORATION CANADA I',
            'ORACLE CORPORATIONS CANADA',
            'ORACLE FOR ADP SOFTWARE',

         ],

         'CANADIAN CORPS OF COMMISSIONAIRES' => [
            'CAN. COMMISSIONAIRES (OTTAWA)',
            'Canadian Commissionaires (Ottawa)',
            'CANADIAN CORP OF COMMISSIONAIRES',
            'CANADIAN CORPS',
            'CANADIAN CORPS OF COMMISSIONAI',
            'CANADIAN CORPS OF COMMISSIONAIRES',
            'CANADIAN CORPS OF COMMISSIONAIRES (HAMILTON)',
            'Canadian Corps of Commissionaires (NB)',
            'CANADIAN CORPS OF COMMISSIONAIRES OTTAWA DIVISION',
            'Canadian Corps. of Commissionaires  (NS)',
            'CDN CORPS OF COMMISSIONAIRES',
            'CDN. CORPS OF COMMISSIONAIRES',
            'Commissionaire Kingston',
            'COMMISSIONAIRE SERVICES',
            'COMMISSIONAIRES',
            'COMMISSIONAIRES (GREAT LAKES)',
            'COMMISSIONAIRES - NS',
            'COMMISSIONAIRES B C',
            'COMMISSIONAIRES BRITISH COLUMBIA',
            'COMMISSIONAIRES GREAT LAKES',
            'COMMISSIONAIRES MANITOBA DIVISION',
            'Commissionaires Montreal',
            'COMMISSIONAIRES NB-PEI DIVISION',
            'COMMISSIONAIRES NEWFOUNDLAND',
            'COMMISSIONAIRES NOVA SCOTIA',
            'COMMISSIONAIRES OF NFLD',
            'COMMISSIONAIRES OTTAWA',
            'COMMISSIONAIRES OTTAWA (D)',
            'COMMISSIONAIRES OTTAWA (SG)',
            'COMMISSIONAIRES QUEBEC',
            'COMMISSIONAIRES VICTORIA',
            'Commissionaires Victoria &',
            'COMMISSIONAIRES, NB/PEI',
            'COMMISSIONAIRES-N. ALBERTA',
            'COMMISSIONAIRES-OTTAWA',
            'COMMISSIONARIE SERVICES',
            'COMMISSIONNAIRES DU QUEBEC',
            'COMMISSIONNAIRES MONTREAL',
            'CORPS CANADIEN    COMMISSIONNAIRE',
            'CORPS CANADIEN   COMMISSIONNAIRE',
            'Corps Canadien Commissionaire',
            'CORPS CANADIEN COMMISSIONNAIRE',
            'CORPS CANADIEN DES COMMISSIONNAIRE',
            'Corps canadien des commissionnaires',
            'Corps Canadiens des Commissionnaires',
            'CORPS COMMISSIONAIRES',
            'Corps des Commissionnaires du Canada',
            'Corps of Commissionaires',
            'OTTAWA DIVISION - CANADIAN CORPS',
            'OTTAWA DIVISION - CANADIAN CORPS OF COMMISSIONAIRES',
            'The British Columbia Corps of Commissionaires',
            'The Canadian Corps of Commissionaires',
            'THE CANADIAN CORPS OF COMMISSIONAIRES/LE CORPS CANADIEN DES COMMISSIONAIRES',
            'THE COMMISSIONAIRES',
            '@CANADIAN CORPS OF COMMISSIONAIRES',
            'B.C. Corps of Commissionaires',
            'BC CORPS OF COMMISSIONAIRES',

            'CANADA CORPS OF COMMISSIONAIRES',
            'CANADAIN CORPS OF COMMISSIONAIRES',
            'CANADIAN COPRS OF COMMISSIONAIRES',
            'CANADIAN CORP OF COMMISSIONAIRES OTTAWA',
            'CANADIAN CORPOS OF COMMISSIONAIRES',
            'CANADIAN CORPS COMMISSIONAIRES',
            'CANADIAN CORPS COMMISSIONAIRES OTTAWA DIVISION',
            'CANADIAN  CORPS OF COMMISSIONAIRES',
            'CANADIAN CORPS OFCOMMISSIONAIRES',
            'CANADIAN CORPS OF COMMISSIONAIRES`',
            'CANADIAN CORPS OF COMMISSIONAIRES        100762517PG',
            'CANADIAN CORPS OF COMMISSIONAIRES-HAMILTON',
            'CANADIAN CORPS OF COMMISSIONAIRES KINGSTON AND REGION',
            'CANADIAN CORPS OF COMMISSIONAIRES KINGSTON & REGION',
            'CANADIAN CORPS OF COMMISSIONAIRES (KINGSTON & REGION DIVISIO',
            'CANADIAN CORPS OF COMMISSIONAIRES NB & PEI',
            'CANADIAN CORPS OF COMMISSIONAIRES NB & PEI DIVISION',
            'CANADIAN CORPS OF COMMISSIONAIRES NL DIVISION',
            'CANADIAN CORPS OF COMMISSIONAIRES NMCI',
            'CANADIAN CORPS OF COMMISSIONAIRES (NORTHERN ALBERTA)',
            'CANADIAN CORPS OF COMMISSIONAIRES-NORTHERN ALBERTA DIVISION',
            'CANADIAN CORPS OF COMMISSIONAIRES NOVA SCOTI',
            'CANADIAN CORPS OF COMMISSIONAIRES NOVA SCOTIA',
            'CANADIAN CORPS OF COMMISSIONAIRES NS DIVISION',
            'CANADIAN CORPS OF COMMISSIONAIRES OTTAWA DEVISION',
            'CANADIAN CORPS OF COMMISSIONAIRES (OTTAWA DIVISION)',
            'CANADIAN CORPS OF COMMISSIONAIRES (SOUTHERN',
            'CANADIAN CORPS OF COMMISSIONAIRES SOUTHERN ALBERTA',
            'CANADIAN CORPS OF COMMISSIONAIRES (WINDSOR)',
            'CANADIAN CRPS COMMISSIONAIRES',
            'CANDIAN CORPS OF COMMISSIONAIRES',
            'CCIDS COMMISSIONAIRES OTTAWA',
            'COMMISSIONAIRES BC',
            'COMMISSIONAIRES (BRITISH COLUMBIA)',
            'COMMISSIONAIRESBRITISH COLUMBIA',
            'COMMISSIONAIRES CORP OF',
            'COMMISSIONAIRES CORPS',
            'COMMISSIONAIRES DIVISION',
            'COMMISSIONAIRES DIVISION D OTTAWA',
            'COMMISSIONAIRES DU QUEBEC',
            'COMMISSIONAIRES (EDMONTON)',
            'COMMISSIONAIRES GEREAT LAKES',
            'COMMISSIONAIRES (GREAAT LAKES)',
            'COMMISSIONAIRES GREAT LAKE ONTARIO',
            'COMMISSIONAIRES  (GREAT LAKES)',
            'COMMISSIONAIRES-GREAT LAKES',
            'COMMISSIONAIRES GREAT LAKES    122971948PG0001',
            'COMMISSIONAIRES GREAT LAKES       122971948PG0001',
            'COMMISSIONAIRES GREAT LAKES CORP',
            'COMMISSIONAIRES HAMILTON',
            'COMMISSIONAIRES (KINGSTON)',
            'COMMISSIONAIRES MANITOBA',
            'COMMISSIONAIRES MANITOBA & NORTHWESTERN ONTARIO',
            'COMMISSIONAIRES MANITOBA & NORTH WESTERN ONTARIO DIVISION',
            'COMMISSIONAIRES NB/PEI DIVISION',
            'COMMISSIONAIRES NORTHERN',
            'COMMISSIONAIRES NOVA SCOITA',
            'COMMISSIONAIRES NOVA SCOTIA DIVISION',
            'COMMISSIONAIRES OF NS',
            'COMMISSIONAIRES (OTTAWA)',
            'COMMISSIONAIRES OTTAWA (CCIDS)',
            'COMMISSIONAIRES OTTAWA COLONADE',
            'COMMISSIONAIRES OTTAWA DIVISION',
            'COMMISSIONAIRES OTTAWA (FP) THE CANADIAN CORPS OF COMMISSIONAIRES',
            'COMMISSIONAIRES OTTAWA (SG) THE CANADIAN CORPS OF COMMISSIONAIRES',
            'COMMISSIONAIRES SASKATCHEWAN',
            'COMMISSIONAIRES SECURITY',
            'COMMISSIONAIRES SECURITY SOLULTIONS',
            'COMMISSIONAIRES SECURITY SOLUTIONS',
            'COMMISSIONAIRES SECURTIY SOLUTIONS',
            'COMMISSIONAIRES SERVICES',
            'COMMISSIONAIRES SERVICES NORTH SASKATCHEWAN',
            'COMMISSIONAIRES SOUTHERN',
            'COMMISSIONAIRES (THE)',
            'COMMISSIONAIRES WINDSOR',
            'CORP COMMISSIONAIRES',
            'CORP OF COMMISSIONAIRES',
            'CORPS CANADIEN DES COMMISSIONAIRES',
            'NB/PEI DIVISION CANADIAN CORPS OF COMMISSIONAIRES',
            'THE CANADIAN CORP OF COMMISSIONAIRES',
            'THE CANADIAN CORPOS OF COMMISSIONAIRES',
            'THE CANADIAN CORPS COF COMMISSIONAIRES',
            'THE CANADIAN CORPS OF  COMMISSIONAIRES',
            'THE CANADIAN CORPS OF COMMISSIONAIRES OTTAWA',
            'THE CANADIAN CORPS OF COMMISSIONAIRES OTTAWA DIVISION',
            'THE CANAIDAN CORPS OF COMMISSIONAIRES',
            'THE CDN CORPS OF COMMISSIONAIRES GLOUCESTER',
            'THE CDN CORPS OF COMMISSIONAIRES OTTAWA ON',
            'THE COMMISSIONAIRES (GREAT LAKES)',
            'THE COMMISSIONAIRES-OTTAWA DIVISIO',
            'THE COMMISSIONAIRES-OTTAWA DIVISION',
            'THE CORPS OF COMMISSIONAIRES',
            'WINDSOR CORPS OF COMMISSIONAIRES',

         ],

         'CDW CANADA' => [

            'CDW',
            'CDW CANADA CORP',
            'CDW CANADA CORPORATION',
            'CDW CANADA (RESELLER OF MICROSOFT)',
            'CDW CDA',
            'FOUR POINT SOLUTIONS C/O CDW CANADA',

         ],

         'TELUS CANADA' => [

            'Telus',
            'TELUS COLLABORATION SERVICES',
            'TELUS COMMUNICATION (B.C.) INC.',
            'TELUS COMMUNICATIONS',
            'TELUS COMMUNICATIONS CO.',
            'TELUS COMMUNICATIONS COMPANY',
            'TELUS COMMUNICATIONS INC',
            'TELUS COMMUNICATIONS INC.',
            'TELUS INTEGRATED COMMUNICATIONS',
            'TELUS MOBILITY',
            'TELUS NATIONAL SYSTEMS INC.',
            'Telus Solutions En Sant',

            'OA-TELUS COMMUNICATIONS COMPANY',
            'SOCIETE TELUS COMMUNICATIONS',
            'TELUS ADVANCED COMMUNICATIONS',
            'TELUS BUSINESS SOLUTIONS',
            'TELUS CANADA',
            'TELUS CLIENT PAYMENT SERVICES',
            'TELUSCLIENT PAYMENT SERVICES',
            'TELUS CLIENT SOLUTIONS',
            'TELUS COMMUNICAITONS',
            'TELUS COMMUNICATION',
            'TELUS COMMUNICATION COMPAGNY',
            'TELUS COMMUNICATION COMPANY',
            'TELUS COMMUNICATION COMPANY O/A TELUS',
            'TELUS COMMUNICATIONS (AMALCO)',
            'TELUS COMMUNICATIONSCOLLABORATION SERVICES',
            'TELUS COMMUNICATIONS  COMPANY',
            'TELUS COMMUNICATIONS COMPANY 7TH FLOOR',
            'TELUS COMMUNICATIONS (EDMONTON)',
            'TELUS COMMUNICATIONS (QUEBEC)',
            'TELUS CORPORATION',
            'TELUS ELECTRICAL SERVICES',
            'TELUS EMERGENCY RESPONSE SUPPORT',
            'TELUS GEOMATICS',
            'TELUS (GEOMATICS)',
            'TELUS HEALTH SOLUTIONS',
            'TELUS HEALTH SOLUTIONS GP',
            'TELUS MOBILITA?',
            'TELUSMOBILITY',
            'TELUS NATIONAL SYSTEM',
            'TELUS NATIONAL SYSTEMSINC',
            'TELUS NATIONAL SYSTEMS/TELUS',
            'TELUS QUA?BEC',
            'TELUS QUEBEC',
            'TELUS SECURITY SOLUTIONS',
            'TELUS SERVICES',
            'TELUS SOLUTIONS DAFFAIRES',
            'TELUS SOLUTIONS EN SANTA?',
            'TELUS SOLUTIONS EN SANTA(C)',
            'TELUS SOLUTIONS EN SANTA(C) SENC',
            'TELUS SOLUTIONS EN SANT(C)',
            'TELUS SOLUTIONS QUEBEC',

         ],

         'VMWARE' => [

            'VMWARE',
            'VMware Inc',
            'VMWare Inc.',
            'VMWARE INTERNATIONAL LIMITED',
            'VM Ware Inc.',

            'COMPUGEN (VMWARE)',
            'EYEDU SOLUTIONS C/O VMWARE',
            'VMWARE CALIFORNIA USA',

         ],

         'MACDONALD DETTWILER AND ASSOCIATES' => [

            'MACDONALD DETTWILER AND',
            'MDA SYSTEMS',
            'MACDONALD DETT',
            'MACDONALD DETTWILER AND ASS',
            'MDA GEOSPATIAL SERVICES',
            'MACDONALD DETWILLER AND',

            'DIGITAL GLOBE C/O MDA GEOSPATIAL SERVICES',
            'MDA',
            'MDA AVIATION REGD',
            'MDA CONTROLS',
            'MDA GEOSPATIAL',
            'MDA GEOSPATIAL SERICES',
            'MDA GEOSPATIAL SERIVES',
            'MDA GEOSPATIAL SERVICE',
            'MDA GEOSPATICAL SERVICES',
            'MDA GEOSPTATIAL SERVICES',
            'MDA SPACE',
            'MACDONALD DETTWILER  AND',
            '"""MACDONALD DETTWILER AND ASSOCIATES               """',
            '"""MACDONALD DETTWILER AND ASSOCIATES"""',
            'MACDONALD DETTWILER AND ASSOCIATES CORPORATION',
            '"""MACDONALD DETTWILER & ASSOCIATES                """',
            '"""MACDONALD DETTWILER & ASSOCIATES"""',
            'MACDONALD DETTWILER & ASSOCIATES',
            'MACDONALD DETTWILER & ASSOCOIATES',
            'MACDONALD DETTWILER SPACE AND',


         ],

         'SASKTEL' => [

            'SASKTEL',
            'SASKATCHEWAN TELECOMMUNICATIONS',
            'SASKATCHEWAN COMMUNICATIONS (SASKTEL)',
            'SASKTEL CMR',
            'SASKTEL INTERNATIONAL',

         ],

         'ELSEVIER BV' => [

            'ELSEVIER  B V',
            'ELSEVIER BV',

            'ELSEVIER',
            'ELSEVIER BV CORPORATE ACCOUNTS',
            'ELSEVIER ENGINEERING INFORMATION',
            'ELSEVIER SCIENCE',
            'ELSEVIER SCIENCE PUBLISHING',

         ],

         'SAS INSTITUTE' => [

            'SAS Institute',
            'SAS INSTITUTE ( CANADA ) INC',
            'SAS INSTITUTE (CANADA) INC',
            'SAS INSTITUTE (CANADA) INC.',
            'SAS Institute Canada',
            'SAS INSTITUTE CANADA INC',
            'SAS INSTITUTE CANADA INC.',
            'SAS Institute Inc.',
            'SAS Instuitute',

            'SAS INSTITUTE (CANADA]',
            'SAS INSTITUTE (CANADA) CON',
            'SAS INSTITUTE (CANADA)INC',
            'SAS INSTITUTE(CANADA)INC',

         ],

         'SCHNEIDER ELECTRIC CANADA' => [

            'SCHNEIDER ELECTRIC CANADA',
            'SCHNEIDER ELECTRIC CANADA INC',
            'SCHNEIDER ELECTRIC CANADA INC.',
            'SCHNEIDER ELECTRIC IT CORPORATION',

            'SCHNEIDER CANADA',
            'SCHNEIDER CANADA SERVICE  DIVISION',
            'SCHNEIDER CANADA-SERVICE DIVISION',
            'SCHNEIDER CANADA SERVICES',
            'SCHNEIDER CANDA SERVICES',
            'SCHNEIDER ELECTRIC',
            'SCHNEIDER ELECTRICAL',
            'SCHNEIDER ELECTRIC CANADA',
            'SCHNEIDER ELECTRIC CANADA; OR SCHNEIDER CANADA SERVICES',
            'SCHNEIDER ELECTRIC  (MISSISSAUGA)',
            'SCHNEIDER ELECTRIC PERU SA',
            'SCHNEIDER ELECTRIC POLSKA SP Z OO',
         ],

         'SECURITAS' => [

            'SECURITAS CANADA LTD',
            'Securitas Canada Ltd.',
            'SECURITAS FRANCE SARL',

            'GROUP 4 SECURITAS GUARDING',
            'SECURITAS ELECTRONIC SECURITY',
            'SECURITAS SA',
            'SECURITAS EGYPT',
            'SECURITAS SAUDI ARABIA CO',
            'SECURITAS SECURITY GUARD (THAILAND)',
            'SECURITAS QUEBEC',
            'SECURITAS',
            'SECURITAS HRVATSKA DOO',
            'SECURITAS UAE LLC',
            'SECURITAS CANADA LIMITED',
            'SECURITAS SISTEMAS DE SEGURIDAD',
            'SECURITAS CR SRO',
            'SECURITAS UAE LLL',
            'SECURITAS CR',
            'MPA SECURITAS',

         ],

         'SHARP ELECTRONICS' => [

            'Sharp Electronics',
            'SHARP ELECTRONICS OF CA',
            'SHARP ELECTRONICS OF CANADA',
            'SHARP ELECTRONICS OF CANADA LT',
            'SHARP ELECTRONICS OF CANADA LTD',
            'Sharp Electronics of Canada Ltd.',
            'SHARP ELECTRONICS OF CDA LTD',

            'PITNEY BOWES (SHARP RESELLER)',
            'SHARP',
            'SHARP AUDIO VISUAL',
            'SHARP BUSINESS FORMS',
            'SHARP C/O PITNEY BOWES OF CANADA',
            'SHARP CANADA',
            'SHARP DIRECT',
            'SHARP DIRECT C/O MELLON BANK',
            'SHARP ELECTONICS OF CANADA',
            'SHARP ELECTRONIC OF CANADA',
            'SHARP ELECTRONICS',
            'SHARP ELECTRONICS (EUROPE) SP ZOO',
            'SHARP ELECTRONICS C/O MELLON BANK NA CANADA BRANCH',
            'SHARP ELECTRONICS OF CAN',
            'SHARP ELECTRONICS OF CANADA (ACTING FOR PITNEY BOWES OF CANADA)',
            'SHARP ELECTRONICS OF CANADA (FORMERLY PITNEY BOWES)',
            'SHARP ELECTRONICS OF CANADA C/O PITNEY BOWES OF CANADA',
            'SHARP ELECTRONICS OF CANADA C/O THE BANK OF NEW YORK MELLON',
            'SHARP ELECTRONICS OF CANADA MISSISSAUGA',
            'SHARP FINANCE',
            'SHARP HOME TECHNOLOGIES',
            'SHARP PITNEY BOWES',
            'SHARP S AUDIO VISUAL',
            'SHARPS',
            'SHARPS AUDIO AND VISUAL',
            'SHARPS AUDIO VIDEO',
            'SHARPS AUDIO VISUAL',
            'SHARPS AUDIO VISUAL (AUDIO VISUAL SYSTEMS INTEGRATION)',
            'SHARPS AUDIO VISUAL SYSTEMS INTEGR',
            'SHARPS AUDIO VSUAL',
            'SHARPS AUDIO-VISUAL',
            'SHARPS AUDIO-VSUAL',
            'SHARPS AUDION VISUAL',
            'SHARPS AUDIOVISUEL',
            'SHARPSS AUDIO VISUAL',

         ],

         'PITNEY BOWES' => [

            'PITNEY BOWES CANADA',
            'PITNEY BOWES OF CAN',
            'PITNEY BOWES OF CANDA',
            'PITNEY BOWES SOFTWARE',
            'PITNEY BOWES MAPINFO',
            'PITNEY BOWES OF CANADA POSTAGE BY PHONE',
            'POSTAGE BY PHONE-PITNEY BOWES LT',
            'PITNEY BOWES CDA',
            'PITNEY BOWES DANKA',
            'PITNEY BOWES HONG KONG',
            'PITNEY BOWES OF CANADA LIMITED',
            'PITNEY BOWES SOFTWARE CANADA',
            'PITNEY BOWES DU CANADA',
            'PITNEY BOWES MAP INFO CANADA',
            'PITNEY BOWES POSTAGE BY PHONE',
            'PITNEY BOWES BUSINESS INSIGHT',
            'PITNEY BOWES GLOBAL',
            'PITNEY BOWES OF CANADA',
            'POSTAGE BY PHONE-PITNEY BOWES',
            'PITNEY BOWES GLOBAL CREDIT SERVICES',
            'PITNEY BOWES LEASING',
            'PITNEY BOWES',
            'POSTAGE BY PHONE/PITNEY BOWES',
            'PITNEY BOWES FINAN',

         ],

         'SHRED-IT' => [

            'SHRED IT',
            'SHRED IT INTERNATIONAL ULC',
            'SHRED-IT',
            'SHRED-IT - INTERNATIONAL INC',
            'Shred-It Canada (Toronto)',
            'SHRED-IT HALIFAX',
            'SHRED-IT INTERNATIONAL',
            'SHRED-IT INTERNATIONAL INC.',
            'Shred-it International ULC',
            'SHRED-IT MONTR��AL',
            'SHRED-IT SOUTHWESTERN ONTARIO',

            'SHRED IT',
            'SHRED-IT MONTREAL',
            'SHRED-TECH',
            'SHRED-IT CANADA',
            'SHRED IT INTERNATIONAL',
            'SHRED-IT BC',
            'SHRED-IT MONCTON',
            'SHRED-IT OTTAWA (C/R 137674)',
            'SHRED-IT INTERNATIONAL UIC',
            'SHRED IT CANADA CORPORATION SECUR IT',
            'SHRED-IT-MONTREAL',
            'SECURIT RECORDS MANAGEMENT SHRED-IT INTERNATIONAL',
            'SHRED-IT CANADA CORPORATION',
            'SHRED-IT A SECURIT COMPANY IT ATLANTIC',
            'SHRED-IT OTTAWA',

         ],

         'SIEMENS' => [

            'SIEMENS',
            'SIEMENS - TECHNOLOGIES',
            'SIEMENS BUILDING TECHNOLOGIES LTD',
            'SIEMENS BUILDING TECHNOLOGIES LTD.',
            'SIEMENS CA LIMITED / LIMITEE',
            'SIEMENS CANADA LIMITED',
            'SIEMENS CANADA LIMITED / LIMITEE',
            'SIEMENS CANADA LTD',
            'SIEMENS CANADA LTD.',
            'SIEMENS DEMAG DELEVAL',
            'SIEMENS INDUSTRY SOFTWARE LTD.',
            'SIEMENS PLM',
            'SIEMENS PRODUCT LIFECYCLE',
            'SIEMENS WATER TECHNOLOGIES CANADA',

            'SIEMENS TECHNOLOGIE DU BACTIMENT',
            'SIEMENS ENTERPRISE COMMUNICATIONS',
            'SIEMENS HEALTHCARE LIMITED',
            'SIEMENS CANADA/LTEE DIVISION TECHNOLOGIES DU BACTIMENT',
            'SIEMENS CANADA LIMITEE',
            'SIEMENS  BUILDING TECHNOLOGIES',
            'SIEMENS HEALTHCARE DIAGNOSTICS',
            'SIEMENS TECHNOLOGIES DU BATIMENT',
            'SIEMENS SPA',
            'SIEMENS WATER TECHNOLOGIES CANADA I',
            'SIEMENS BUILDING AUTOMATION',
            'SIEMENS CANADA LIMITED (OTTAWA)',
            'SIEMENS BUILDING TECHNOLOGIES LANDIS DIVISION',
            'SIEMENS INDUSTRY SOFTWARE/SIEMENS LOGICIELS (INDUSTRIE) LTEE',
            'SIEMENS WESTINGHOUSE TECHNICAL',
            'SIEMENS PRODUCT LIFECYCLE MANAGEMENT SOFTWARE',
            'SIEMENS LIMITED KOREA',
            'SIEMENS TECHNOLOGIES DU BATIMENT LTEE',
            'SIEMENS IT SOLUTIONS & SERVS',
            'SIEMENS CANADA LIMITED SIEMENS CANADA LIMITA?E',
            'SIEMENS WATER TECHNOLOGIES CORP',
            'SIEMENS (LANDIS & STAEFA)',
            'BJ SIEMENS CERBERUS ELECTRONICS',
            'SIEMENS PRODUCT LIFECYCLE MANAGEMENT SOFTWARE (CA)',
            'SIEMENS HEALTHCARE',
            'SIEMENS BUILDING TECH TD',
            'SIEMENS TECHNOLOGIE BACTIMENTS',
            'SIEMENS BUILDING TECHNOLOGIESSIEMENS TECHNOLOGIES DU BATIMENT',
            'SIEMENS BUILDING TECHNOLOGIES-',
            'SIEMENS TECHNOLOGIES DU BACTIMENT LTA(C)E',
            'SIEMENS PLM SOFTWARE (CA)',
            'SIEMENS WESTINGHOUSE TECHNICAL SERVICES',
            'SIEMENS HEALTHCARE LIMITED/ SIEMENS SANTA(C) LIMITA(C)E',
            'SIEMENS BUILDING TECHN',
            'SIEMENS',
            'SIEMENS BUILDING TECHNOLOGIES(TIANJ',
            'SIEMENS BUILIDNG TECHNOLOGIES',
            'SIEMENS WATER TECHNOLOGIES',
            'SIEMENS WATER TECHNOLGIES CANADA/SIEMENS TECHNOLOGIESDES EAUX CANADA',
            'SIEMENS TECHNOLOGIES DU BATIMENTS L',
            'SIEMENS MEDICAL SOLUTIONS DIAGNOSTI',
            'SIEMENS INDUSTRIAL SERVICES',
            'SIEMENS BUILDING',
            'SIEMENS BUILDING TECHNOLOGIES SIEMENS TECHNOLOGIES DU BACTIMENT LTA(C)E',
            'SIEMENS TECHNOLOGIE',
            'SIEMENS BUILDING TECHNOLOGIESLTD',
            'SIEMENS WATER TECHNOLGIES CANADA/SIEMENS TECHNOLOGIESDES EAUX CA',
            'SIEMENS BUILDING TECHNOLOGIES L',
            'SIEMENS CANADA LIMITEE (QUEBEC)',
            'SIEMENS BUILDING TECH',
            'SIEMENS CANADA LIMITED (BRAMPTON)',

         ],

         'SOFTCHOICE' => [

            'CARAHSOFT TECHNOLOGY CORP C/O SOFTCHOICE',
            'FOUR POINTS SOLUTIONS C/O SOFTCHOICE CORPORATION',
            'MICROSOFT CORP/ C/O SOFTCHOICE CORP',
            'MICROSOFT CORPORATION C/O SOFTCHOICE',
            'MICROSOFT LICENSING GP C/O SOFTCHOICE CORPORATION',
            'MICROSOFT (SOFTCHOICE)',
            'MSLIGP/ SOFTCHOICE CORPORATION',
            'SOFTCHOICE CANADA',
            'SOFTCHOICE COMPANY',
            'SOFTCHOICE COPORATION',
            'SOFTCHOICE COROPORATION',
            'SOFTCHOICE CORP',
            'SOFTCHOICE CORP (CANADA)',
            'SOFTCHOICE CORPORATION',
            'SOFTCHOICE CORPORATION ATT: JANICE RAKOWSKI',
            'SOFTCHOICE CORPORATION (CAD)',
            'SOFTCHOICE CORPORATION (RESELLER OF IBM PRODUCTS)',
            'SOFTCHOICE CORP SEE 117956',
            'SOFTCHOICE (IBM RESELLER)',
            'SOFTCHOICE LP',
            'SOFTCHOICE (OTTAWA',
            'SOFTCHOICE RESELLER FOR LENOVO CANADA',
            'SOFTCHOICE (RESELLER OF ACL IN CANADA)',
            'SOFTCHOICE-UNIS LUMIN',
            'SOFTCHOICE (VANCOUVER)',

         ],

         'INSIGHT SOFTWARE CANADA' => [

            'INSIGHT SOFTWARE CANADA',
            'INSIGHT SOFTWARE SPECTRUM',
            'INSIGHT(SOFTWARE SPECTRUM)',
            'INSIGHT (SOFTWARE SPECTRUM  CANADA)',
            'INSIGHT (SOFTWARE SPECTRUM CANADA)',
            'MSLIGP O/A MICROSOFT  LICENSING C/O INSIGHT SOFTWARE CANADA',
            'MSLIGP O/A MICROSOFT LICENSING C/O INSIGHT SOFTWARE CANADA',

            'SOFTWARE SPECTRUM',
            'SOFTWARE SPECTRUM CANADA',
            'SOFTWARE SPECTRUM CANADA-',
            'MSLIGP O/A MICROSOFT LICENSING C/O SOFTWARE SPECTRUM',

         ],

         'HITACHI DATA SYSTEMS' => [
            'HITACHI DATA SYSTEMS',
            'HITACHI DATA SYSTEMS INC.',
            'HITACHI HIGH TECHNOLOGIES CANADA INC.',
            'HITACHI HIGH-TECHNOLOGIES CANADA',

            'HITACHI  DATA SYSTEMS',
            'HITACHI DATA SYSTEM',
            'HITACHI DATA SYSTEMS',
            'HITACHI DATA SYSTEMS T46152',
            'HITACHI SOFTWARE ENGINEERING AMERICA',
            'HITACHI DATAT SYSTEMS',
            'HITACHI HIGH TECHNOLOGIES',
            'HITACHI HIGH-TECHNOLOGIES',
            'HITACHI VANTARA',
            'HITACHI HIGHT TECHNOLOGIE',
            'HITACHI SOFTWARE ENGINEERING AMERIC',
         ],

         'SYMANTEC' => [
            'SYMANTEC',
            'SYMANTEC CORPORATION',
            'SYMANTEC CORPORATION (CANADA)',
            'SYMANTECH',
            'SYMANTEC CORP',
         ],

         'ADGA GROUP' => [
            'ADGA GROUP CONSULTANTS INC',
            'ADGA GROUP CONSULTANTS INC.',
            'ADGA GROUP THE',

            'ADGA (GROUP)',
            'ADGA GROUP CONSULTING',
            'CREEADGA',
            'ADGA',
            'ADGA GROUP',
            'ADGA GROUP CONSULTANTS 116 ALBERT ST SUITE 600',
            'ADGA (QUEBEC) LTEE',
            'GROUPE ADGA',
            'ADGA CONSULTING GROUP',
            'ADGA GROUP CONSULTANT',

         ],

         'PRICEWATERHOUSE COOPERS' => [
            'Pricewaterhouse Coopers',
            'PRICEWATERHOUSE COOPERS INC',
            'PRICEWATERHOUSE COOPERS LLP',
            'Pricewaterhouse Coopers Llp.',
            'PRICEWATERHOUSECOOPERS',
            'PRICEWATERHOUSECOOPERS (PWC) LLP',
            'PRICEWATERHOUSECOOPERS LLP',
            'PRICE WATER HOUSE',
            'PRICE WATERHOUSE COOPERS LLP',
            'PwC Consulting, A Business',
            'PWC Management Services LP',

            'PRICEWATERHOUSECOOPERS AUDIT SRL',
            'PRICEWATERHOUSE COOPERS',
            'PRICEWATERHOUSE COOPERS JJP',
            'PRICEWATERHOUSECOOPERS LDA',
            'PRICEWATERHOUSECOOPERS LIMITED',
            'PRICEWATERHOUSECOOPERLLP',
            'PRICEWATERHOUSECOOPER LLP',
            'PWC MANAGEMENT SERVICES LP (OPERATING AS : PRICEWATERHOUSECOOPERS LLP)',
            'PRICEWATERHOUSE COPPERS LLP',
            'PRICEWATERHOUSE COOPERS SRL',
            'PRICEWATERHOUSECOOPERS(PWC)',
            'PRICEWATERHOUSE',
            'PRICEWATERHOUSECOOPERSPWC CENTRAL ACCOUNTING',
            'PRICEWATERHOUSE COOPER',
            'PRICEWATERHOUSECOOPERS TRUSTEE IN BANKRUPTCY',
            'PRICEWATERHOUSE COOPERS (PWC) LLP',
            'PWC CONSULTING',
            'PWC',
            'PRICEWATERHOUSECOOPERS(PWC)',
            'PRICEWATERHOUSECOOPERSPWC CENTRAL ACCOUNTING',
            'PWC MANAGEMENT SERVICES LP (OPERATING AS : PRICEWATERHOUSECOOPERS LLP)',
            'PRICEWATERHOUSE COOPERS (PWC) LLP',

         ],

         'BELL TEXTRON HELICOPTER' => [
            'BELL HELICOPTER',
            'BELL HELICOPTER TEXTRON CANADA LTD',
            'BELL HELICOPTER TEXTRON INC.',
         ],

         'MCKESSON CANADA' => [
            'McKesson  Canada',
            'MCKESSON AUTOMATION CANADA',
            'MCKESSON CA',
            'MCKESSON CA CORPORATION',
            'MCKESSON CANADA',
            'MCKESSON CANADA CORPORATION',
            'MCKESSON',
            'MCKESSON AUTOMATION CANADA CORPORATION',
            'MCKESSON CANADA',
            'MCKESSON DISTRIBUTION PARTNERS',
         ],

         'RANDSTAD' => [
            'RANDSTAD',
            'RANDSTAD CANADA',
            'RANDSTAD INTERIM INC',
            'RANDSTAD INTERIM INC.',
            'RANDSTAD PARC JARRY',
            'ADRM TEC AND RANDSTAD INTERIM',
            'ADRM TECHNOLOGY AND RANDSTAD',
            'ADRM TECHNOLOGY AND RANDSTAD I',
            'ADRM TECHNOLOGY CONSULTING GROUP CORP AND RANDSTAD INTERIM',
            'ADRM TECHNOLOGY CONSULTING GROUP CORP AND RANDSTAD INTERIM (JOIN',
            'RANDSTAD',
            'RANDSTAD BRASIL RECURSOS HUMANOS',
            'RANDSTAD CANADA GROUP',
            'RANDSTAD FRANCE INTERIM SA',
            'RANDSTAD INTERIM C/O SAPPHIRE CANADA A DIVISION OF RANDSTAD INTERIM',
            'RANDSTAD INTERIM/RANDSTAD INTERIM',
            'RANDSTAD INTERIM- TEMP HELP',
            'RANDSTAD OTTAWA',
            'RANDSTAD RECRUTEMENT',
            'RANDSTAD TECHNOLOGIES',
            'RANDSTAD WORK SOLUTIONS',
            'TITUS INTERNATIONAL RANDSTAD',
         ],

         'COMPUTER ASSOCIATES CANADA' => [
            'COMPUTER ASSOCIATES CANADA COM',
            'COMPUTER ASSOCIATES CANADA COMPANY',
            'Computer Associates Canada Ltd.',
            'COMPUTER ASSOCIATES',
            'COMPUTER ASSOCIATES CANADA',
            'COMPUTER ASSOCIATES CANADA CO',
         ],

         'COMPUCOM CANADA' => [
            'COMPUCOM',
            'COMPUCOM CANADA',
            'COMPUCOM CANADA CO',
            'COMPUCOM CANADA CO.',
            'COMPUCOM CANADA',
            'COMPUCOM CANADA CORP',
            'COMPUCOM CORPORATION',
            'COMPUCOM SYSTEM',
            'COMPUCOM SYSTEMS',
         ],

         'TERAMACH TECHNOLOGIES' => [
            'TERAMACH',
            'TERAMACH TECHNOLOGICS INC',
            'TERAMACH TECHNOLOGIES INC',
            'TERAMACH TECHNOLOGIES INC.',
            'Teramach Techonologies',
            'TERAMACH TEC',
            'TERAMACH TECHBOLOGIES',
            'TERAMACH TECHNOLOGIE',
            'TERAMACH TECHNOLOGIES',
            'TERAMACH TECHNOLOGIES-',
         ],

         'MODIS CANADA' => [
            'MODIS  CANADA INC.',
            'MODIS CANADA INC',
            'MODIS CANADA INC.',

            'AJILON CANADA (MODIS)',
            'MODIS',
            'MODIS AJILON',
            'MODIS CANADA',
            'MODIS CDA',
            'TEAM MODIS',
         ],

         'MAPLESOFT CONSULTING' => [
            'MAPLESOFT',
            'Maplesoft Administrative Services',
            'MAPLESOFT ADMINISTRATIVE SERVICES INC',
            'MAPLESOFT CONSULTING',
            'MAPLESOFT CONSULTING INC.',
            'MAPLESOFT LEGAL SUPPORT SERVICES',
            'Maplesoft Technology Inc.',

            'MAPLESOFT ADMINISTRATIVE SERVICES I',
            'MAPLESOFT COMPUTING',
            'MAPLESOFT CONSULTING',
            'MAPLESOFT CONSULTING-',
            'MAPLESOFT CONSULTING O/A MAPLESOFT GROUP',
            'MAPLESOFT GROUP',
            'MCS MAPLESOFT CONSULTING',
            'MSC MAPLESOFT',
            'MSC MAPLESOFT CONSULTING',
            'MSC  MAPLESOFT CONSULTING IN',
            'TBIPS MAPLESOFT CONSULTING',
         ],

         'MobilShred (Recall)' => [
            'MobilShred (Recall)',
            'MobilShred Inc (Recall)',
            'MobilShred Inc.',
            'Mobilshred Inc. (Operating as Recal',
            'Mobilshred Inc. (Operating as Recall)',
            'MobilShred Inc. (Recall)',
         ],

         'G4S SECURITY SERVICES' => [
            'G4S CASH SOLUTIONS (CANADA)',
            'G4S SECURITY SERVICES (CANADA)',
            'G4S SECURITY SERVICES (CANADA) LTD.',

            'G4S',
            'G4S CASH SERVICES (CANADA)',
            'G4S CASH SERVICES (CANADA) LIMITED',
            'G4S CASH SOLUTIONS CANADA',
            'G4S CASH SOLUTIONS (CANADA]',
            'G4S DRC SARL',
            'G4S FACILITIES MANAGEMENT',
            'G4S GUARDING SECURITY SERVICES SA',
            'G4S GUVENLIK HIZMETLERI AS',
            'G4S INTEGRATED SERVICES GMBH',
            'G4S JAMAICA LIMITED',
            'G4S PERU SA',
            'G4S QATAR SPC',
            'G4S RISK MANAGEMENT',
            'G4S SECURE SOLUTION (INDIA) PRIVATE',
            'G4S SECURE SOLUTIONS',
            'G4S SECURE SOLUTIONS AG',
            'G4S SECURE SOLUTIONS BANGLADESH (P)',
            'G4S SECURE SOLUTIONS(BARBADOS)',
            'G4S SECURE SOLUTIONS (CANADA)',
            'G4S SECURE SOLUTIONS (CANADA)/G4S SOLUTIONS DE SECURITE (CANADA)',
            'G4S SECURE SOLUTIONS (CI) SA',
            'G4S SECURE SOLUTIONS (INDIA) PRIVAT',
            'G4S SECURE SOLUTIONS INDIA PRIVATE',
            'G4S SECURE SOLUTIONS INT JORDAN',
            'G4S SECURE SOLUTIONS LIMITED',
            'G4S SECURE SOLUTIONS SA',
            'G4S SECURE SOLUTIONS SDN BHD',
            'G4S SECURE SOLUTIONS (TAIWAN) LIMIT',
            'G4S SECURE SOLUTIONS ZAMBIA LIMITED',
            'G4S SECURE SOLUTION (USA)',
            'G4S SECURITY SERVICES',
            'G4S SECURITY SERVICES A/S',
            'G4S SECURITY SERVICES BANGLADESH',
            'G4S SECURITY SERVICES (BDOS)',
            'G4S SECURITY SERVICES (CANADA]',
            'G4S SECURITY SERVICES CIAA',
            'G4S SECURITY SERVICES GH',
            'G4S-SECURITY SERVICES MOCAMBIQUE',
            'G4S SECURITY SOLUTIONS',
            'G4S SECURITY SOLUTIONS (CANADA)',
            'G4S SECURITY SYSTEMS',
            'G4S SERVICES DE SA(C)CURITA(C) (QUA(C)BEC)',
            'G4S SOLUCIONES DE SEGURIDAD SA',
            'G4S ZHEJIANG SECURE SOLUTIONS CO',
            'PT G4S SECURITY SERVICES',
            'SECURICOR CASH SERVICE G4S CASH SOLUTIONS (CANADA)',
         ],

         'MARCOMM' => [
            'MARCOMM',
            'Marcomm Fibre Optics',
            'MARCOMM FIBRE OPTICS INC.',
            'MARCOMM INC',
            'MARCOMM INC.',
            'MARCOMM SYSTEMS GROUP INC',
            'MARCOMM INTEGRATED BUSINESS SOLUTIONS',
            'MARCOMM SC 360',
         ],

         'CONEXSYS' => [
            'CONEXSYS COMMUNICATION LTD.',
            'Conexsys Communications',
            'CONEXSYS COMMUNICATIONS LIMITED',
            'CONEXSYS COMMUNICATIONS LTD',
            'CONEXSYS COMMUNICATIONS LTD.',
            'CONEXSYS COMMUNCATIONS',
            'CONEXSYS COMMUNICATIONS LIMITE',
         ],

         'PROVINCIAL AIRLINES' => [
            'PROVINCIAL AEROSPACE LTD (PAL)',
            'PROVINCIAL AIRLINES LTD',
            'PROVINCIAL AIRLINES LIMITED',
         ],

         'ADVANCED CHIPPEWA TECHNOLOGIES' => [
            'ADVANCED CHIPPEWA TECHNOLOGI',
            'ADVANCED CHIPPEWA TECHNOLOGIES',
            'ADVANCED CHIPPEWA TECHNOLOGIES INC',
            'ADVANCED CHIPPEWA TECHNOLOGIES INC.',

            'ADVANCEC CHIPPEWA TECHNOLOGIES',
            'ADVANCE CHIPPEWA TECHNOLOGIES',
            'ADVANCED CHIPPEWA',
            'ADVANCED CHIPPEWA TACHNOLOGIES',
            'ADVANCED CHIPPEWA TECH',
            'ADVANCED CHIPPEWA TECHNOLIGIES',
            'ADVANCED CHIPPEWATECHNOLOGIES',
            'ADVANCED CHIPPEWA TECHNOLOGIES',
            'ADVANCED CHIPPEWA TECHNOLOGIES/',
            'ADVANCED CHIPPEWA TECHNOLOGIES 4165047 CANADA IN JOINT VENT',
            'ADVANCED CHIPPEWA TECHNOLOGIES (ACT)',
            'ADVANCED CHIPPEWA TECHNOLOGY',
            'ADVANCED CHIPPEWA TECHNOLOICS',
            'ADVANCED CHIPPEWA TECHOLOGIES',
            'ADVANCED CHIPPEWA TECJNOLOGIES',
         ],

         'DNR CONSULTING GROUP' => [
            'DNR CONSULTING GROUP',
            'DNR CONSULTING GROUP INC.',
            'DNR GROUP',
            'DNR GROUP INC.',
            'DNR CONSUTING GROUP',
            'DNR-GROUP',
         ],

         'NOVELL CANADA' => [
            'Novell',
            'NOVELL CANADA LTD',
            'NOVELL CANADA LTD.',
            'NOVELL CANADA,LTD.',
            'NOVELL CANADA LIMITED',
            'NOVELL CANADA (ONTARIO)',
         ],

         'MCAFEE INTERNATIONAL' => [
            'MCAFEE INTERNATIONAL B.V.',
            'MCAFEE IRELAND LIMITED',
            'MCAFEE INTERNATIONAL',
            'MCAFEE IRELAND',
         ],

         'DELOITTE AND TOUCHE' => [
            'Deloitte',
            'DELOITTE & TOUCHE',
            'DELOITTE & TOUCHE LLP',
            'DELOITTE & TOUCHE, LLP',
            'Deloitte and Touche',
            'DELOITTE AND TOUCHE LLP',
            'DELOITTE AND TOUCHE, LLP',
            'DELOITTE CONSULTING INC.',
            'DELOITTE INC',
            'Deloitte Inc.',
            'Deloitte LLP',
            'DELOITTE AND TOUCHE',
            'DELOITTE AND TOUCHE LLP O/A DELOITTE TOUCHE TOHMATSU',
            'DELOITTE CONSULTING LLP',
            'DELOITTE FINANCE',
            'DELOITTE LLP (OTTAWA)',
            'DELOITTE MANAGEMENT SERVICES LP',
            'DELOITTE RECAP LLC',
            'DELOITTE SENCRL',
            'DELOITTE SENCRL/SRL',
            'DELOITTE & TOUCH',
            'DELOITTE & TOUCHE CONSULTING',
            'DELOITTE & TOUCHE CONSULTING GROUP',
            'DELOITTE  & TOUCHE(DO NOT USE)',
            'DELOITTE & TOUCHE FORENSIC',
            'DELOITTE & TOUCHE GMBH',
            'DELOITTE  & TOUCHE LLP',
            'DELOITTE &TOUCHE LLP',
            'DELOITTE TOUCHE LLP',
            'DELOITTE & TOUCHE SRL',
            'DELOITTE TOUCHE TOHMATSU',
            'DELOITTE TOUCHE TOHMATSU CERTIFIED',
            'DELOITTE TOUCHE TOHMATSU CERTIFIED PUBLIC ACCOUNTANTS',
            'SAMSON BELAIR DELOITTE & TOUCHE',
            'TEAM DELOITTE-EWA',
            'TEAM DELOITTE-EWA (DELOITTE & TOUCHE LLP AND ELECTRONIC WARFARE ASSOCI',
         ],

         'ATCO FRONTEC' => [
            'ATCO FRONTEC CORP.',
            'ATCO STRUCTURES & LOGISTICS LTD.',
            'ATCO STRUCTURES AND LOGISTICS',
            'ATCO FRONTEC SERVICES',
            'ATCO FRONTEC CORPORATION',
         ],

         'IBISKA TELECOM' => [
            'IBISKA',
            'IBISKA TELECOM INC.',

            'ELYTRA ENTREPRISES & IBISKA TELECOM JV',
            'ELYTRA-IBISKA JV (ELYTRA ENTERPRISE',
            'ELYTRA-IBISKA JV (ELYTRA ENTERPRISES AND IBISKA TELECOM IN',
            'ELYTRA INTERPRISES AND IBISKA JV',
            'IBISKA TELECOM',
            'IBISKA TELECOM AND C M AS A CONTRACTUAL JOINT VENTURE',
            'IBISKA TELECOM AND CM IN JOINT VENTURE',
         ],

         'OEI KRUEGER' => [
            'OEI',
            'OEI KRUEGER INTERNATIONAL INC',
         ],

         // REF:
         // https://www2.excelitr.com/About/OurCompany
         'EXCEL HUMAN RESOURCES' => [
            'EXCEL HR',
            'Excel Human Resources',
            'EXCEL HUMAN RESOURCES INC',
            'EXCEL HUMAN RESOURCES INC.',
            'Excel Human Ressources Inc',
            'Excel Human Ressources Inc.',

            'ALTIS-EXCEL',
            'ALTISEXCELHR IN JOINT VENTURE',
            'ALTIS HR AND EXCEL HR IN JOINT VENTURE',
            'ALTIS HR AND EXCEL IN JOINT VENTURE',
            'ALTISHR EXCELHR IN JOINT VENT',
            'ALTISHR EXCELHR IN JOINT VENTURE',
            'ALTIS HRO/EXCEL HR/ALTIS HR',
            'ALTIS HRO/EXCEL HR/ALTIS HR (JV)',
            'ALTIS HR (OTTAWA)INC & EXCELHR-JOINT VENTURE',
            'ALTIS HUMAN RESOURCES AND EXCEL HUMAN RESOURCES',
            'ALTIS HUMAN RESOURCES (OTTAWA) AND EXCEL HUMAN RESOURCES IN JOINT VENTURE',
            'ALTIS HUMAN RESOURCES (OTTAWA) EXCEL HUMAN RESOURCES AND ALTIS HUMAN',
            'EXCEL',
            'EXCELHR',
            'EXCELHR AND/OR EXCEL INFORMATION TECHNOLOGY RESOURCES (EXCELITR) AND/O',
            'EXCEL HR COMPUTER SUPPORT',
            'EXCEL HR/ITR',
            'EXCEL HR SYLVIE POTVIN',
            'EXCEL HUMANE RESOURCES',
            'EXCEL HUMAN RESOUCES',
            'EXCEL HUMAN RESOURCE',
            'EXCEL HUMAN RESOURCES',
            'EXCEL HUMAN RESOURCES-',
            'EXCEL HUMAN RESOURCES 102 BANK ST SUITE 300',
            'EXCEL HUMAN RESOURCES BRANCH',
            'EXCEL HUMAN RESOURCES (EXCELITR)',
            'EXCEL HUMAN RESOURCES IT',
            'EXCEL HUMAN RESOURCES (OTTAWA)',
            'EXCEL HUMAN RESOURCES (PP)',
            'EXCEL HUMAN RESOURECES',
            'EXCEL HUMAN RESOURSE',
            'EXCEL HUNMAN RESOURCES',
            'EXCEL INFORMATION TECHNOLOGY',
            'EXCEL INFORMATION TECHNOLOGY RESOURCES',
            'EXCELITR',
            'EXCEL ITR',
            'EXCEL IT RESOURCES',
            'EXCEL ITR-EXCEL INFORMATION TECHNOLOGY RESOURCES',
            'EXCELL HR',
            'EXCELL HUMAN RESOURCES',
            'EXCEL PERSONNEL',
            'EXCEL TEMP HELP',
            'HR EXCEL',
            'TBIPS EXCEL ALTIS HUMAN RESOURCES',

         ],

         'MINDWIRE SYSTEMS' => [
            'MINDWIRE',
            'Mindwire (Zylog)',
            'MINDWIRE SYSTEMS LTD',
            'MINDWIRE SYSTEMS LTD.',
            'MINDWIRE SYSTEMS (DBA ZYLOG OTTAWA)',
            'ZYLOG SYSTEM (OTTAWA)',
            'ZYLOG SYSTEMS',
            'ZYLOG SYSTEMS OTTAWA',
            'ZYLOG SYSTEMS (OTTAWA)',
            'ZYLOG SYSTEMS (OTTAWA]',
            'ZYLOG SYSTEMS (OTTAWA) LIMITED',
            'ZYLOG SYSTEMS (OTTAWA) O/A BRAINHUNTER',
         ],

         'EBSCO CANADA' => [
            'EBSCO Canada',
            'EBSCO Canada Ltd',
            'EBSCO CANADA LTD.',
            'EBSCO CANADA LTEE',
            'Ebsco Canada Lt̩e',
            'EBSCO CANADA LT��E',
            'EBSCO PUBLISHING',
            'EBSCO',
            'EBSCO CA',
            'EBSCO CANADA',
            'EBSCO CANADA-',
            'EBSCO CANADA LIMITED',
            'EBSCO CANADA LTA?E',
            'EBSCO CANADA LTE',
            'EBSCO INFORMATION SERVICES',
         ],

         'CISTEL TECHNOLOGY' => [
            'Cistel',
            'CISTEL TECHNOLOGY',
            'Cistel Technology Inc',
            'CISTEL TECHNOLOGY INC TECSIS CORPORATION IN JOINT VENTURE',
            'CISTEL TECHNOLOGY INC.',
            'CISTEL A TECHNOLOGY',
            'CISTEL INFORMATION SYSTEMS',
            'CISTEL TECH',
            'CISTEL TECHNOLOGY',
            'CISTEL TECHNOLOGY NC',
            'CISTEL TECHNOLOGY & TECSIS CORPORATION',
         ],

         'CITRIX' => [
            'Citrix',
            'CITRIX ONLINE LLC',
            'CITRIX SYSTEMS INC',
            'CITRIX SYSTEMS INC.',
            'CITRIX SYSTEMS, INC.',
            'CITRIX (METACOMM)',
         ],

         'ECLIPSYS SOLUTIONS' => [
            'ECLIPSYS',
            'ECLIPSYS SOLUTIONS INC',
            'ECLIPSYS SOLUTIONS INC.',
            'ECLIPSYS SOLUTION',
            'ECLIPSYSA?SOLUTIONS',
         ],

         'TRANSPOLAR TECHNOLOGY' => [
            'TRANSPOLAR TECHNOLOGY CORP',
            'TRANSPOLAR TECHNOLOGY CORP.',
            'TRANSPOLAR TECHNOLOGY CORPORATION',
            'THE HALIFAX GROUP TRANSPOLAR',
            'THE HALIFAX GROUP TRANSPOLAR IN',
            'TRANSPOLAR',
            'TRANSPOLAR AND HALIFAX GROUP IN JOINT VENTURE',
            'TRANSPOLAR CANADA',
            'TRANSPOLAR TECHNOLOGY',
            'TRANSPOLAR TECHNOLOGY CORPORAT',
            'TRANSPOLAR TECHNOLOLGY CORPORATION',
            'TRANSPOLAR THE HALIFAX GROUPJOINT VENTURE',
         ],

         'MOTOROLA SOLUTIONS CANADA' => [
            'MOTOROLA CANADA LTD',
            'MOTOROLA NATIONAL PARTS',
            'MOTOROLA SOLUTIONS CANADA INC',
            'MOTOROLA SOLUTIONS CANADA INC.',

            'MOTOROLA',
            'MOTOROLA CANADA LIMITED',
            'MOTOROLA CANADA LIMITEE',
            'MOTOROLA CANDA',
            'MOTOROLA CNADA',
            'MOTOROLA- MDUG',
            'MOTOROLA SOLTUIONS CANADA',
            'MOTOROLA SOLUCTIONS CANADA',
            'MOTOROLA SOLUTIONS',
            'MOTOROLA SOLUTIONS CANADA',
            'MOTOROLA SOLUTIONS CANADIAN',
            'MOTOROLA SOLUTIONS CNAADA',
         ],

         'SALVATION ARMY' => [
            'SALVATION ARMY',
            'SALVATION ARMY ARC',
            'SALVATION ARMY BELKIN HOUSE',
            'SALVATION ARMY BOOTH CENTRE BRANTFORD',
            'SALVATION ARMY CENTRE OF HOPE',
            'SALVATION ARMY CORRECTIONAL &',
            'SALVATION ARMY CORRECTIONAL AND JUSTICE SERVICES GREENFIELD HOUSE THE',
            'SALVATION ARMY HARBOUR LIGHT',
            'SALVATION ARMY HARBOUR LIGHTS CORP',
            'SALVATION ARMY WAGNER COTTAGE',

            'THE GOVERNING COUNCIL OF THE SALVATION ARMY IN CANADA',
            'GOVERNING COUNCIL OF SALVATION ARMY IN CANADA',
            'THE SALVATION ARMY CORRECTIONAL AND JUSTICE SERVICES GREENFIELD HOUSE',
            'THE SALVATION ARMY COMMUNITY SERVICES CALGARY',
            'THE SALVATION ARMY NEWFOUNDLAND WEST DIVISIONAL HEADQUARTERS',
            'THE SALVATION ARMY',
            'SALVATION ARMY TERRITORIAL HEADQUARTERS',

         ],

         'VERITAS TECHNOLOGIES' => [
            'Veritas',
            'VERITAS TECHNOLOGIES LLC',
            'VERITAS SOFTWARE',
            'VERITAS SOFTWARE (CANADA)',
            'VERITAS SOFTWARE CORPORATION',
            'VERITAS SOFTWARE GLOBAL CORP',
            'VERITAS SOFTWARE GLOBAL CORPORATION',
            'VERITAS SOFTWARE TECHNOLOGY',
            'VERITAS SOFTWARE TECHNOLOGY CORP',
            'VERITAS SOFTWARE TECHNOLOGY CORPORATION',
            'VERITAS TECHNOLOGIES',
         ],

         'SIERRA SYSTEMS GROUP' => [
            'SIERRA SYSTEMS',
            'SIERRA SYSTEMS GROUP INC',
            'SIERRA SYSTEMS GROUP INC.',
            'SIERRA SYSTEMS CONSULTANTS',
            'SIERRA SYSTEMS GROUP XML',
            'SIERRA SYSYTEMS GROUP',
         ],

         'IRVING SHIPBUILDING' => [

            'IRVING SHIPBUILDING',
            'IRVING SHIPBUILDING\LES CHANTIERS MARITIME IRVING',
            'IRVING SHIPBUILDING INDUSTRIES',
            'IRVING SHIP BUILDING',

         ],

         'D & H PARTNERSHIP' => [
            'D&H PARTNERSHIP',
            'D & H PARTNERSHIP',

         ],

         'GENERAL DYNAMICS' => [

            'GENERAL DYNAMICS ORDNANCE AND TACTICAL SYSTEMS CANADA',
            'GENERAL DYNAMICS LAND SYSTEMS',
            'GENERAL DYNAMICS LAND SYSTEM CANADA CORPORATION',
            'GENERAL DYNAMICS ORDNANCE AND',
            'GENERAL DYNAMICS INFORMATION TECHNOLOGY CANADA',
            'GENERAL DYNAMICS MISSION SYSTEMS IN',
            'GENERAL DYNAMICS COMMUNICATION SYSTEMS',
            'GENERAL DYNAMICS DECISIONS SYSTEMS',
            'GENERAL DYNAMICS',
            'GENERAL DYNAMICS LAND SYSTEMS CANADA',
            'GENERAL DYNAMICS MISSION SYSTEMS CANADA',
            'GENERAL DYNAMICS LAND',
            'GENERAL DYNAMICS SANTA BARBARA SISTEMAS GMBH',
            'GENERAL DYNAMICS MISSION SYSTEM',
            'GENERAL DYNAMICS GLOBAL IMAGING TECHNOLOGIES',
            'GENERAL DYNAMICS (C4 SYSTEMS)',
            'GENERAL DYNAMICS PRODUITS DE DEFENSE ET SYSTEMES TACTIQUES CANADA VA',
            'GENERAL DYNAMICS SATCOM',
            'GENERAL DYNAMICS C4 SYSTEMS',
            'GENERAL DYNAMICS OTS VALLEYFIELD',
            'GENERAL DYNAMICS ARMAMENT AND TECHNICAL PRODUCTS',
            'GENERAL DYNAMICS MISSION',
            'GENERAL DYNAMICS ADVANCED INFORMATION SYSTEMS',
            'GENERAL DYNAMICS EUROPEAN LAND SYSTEMS',
            'GENERAL DYNAMICS MISSION SYSTEMS',
            'GENERAL DYNAMICS LAND SYSTEMS CANADA CORPORATION',
            'GENERAL DYNAMICS INFORMATION',
            'GENERAL DYNAMICS CANADA',
            'GENERAL DYNAMICS EUROPEAN',
            'GENERAL DYNAMICS ADVANCED INFORMATION SYSTEMS (GDAIS)',
            'GENERAL DYNAMICS ORDNANCE AND TACTICAL SYSTEMS',
            'GENERAL DYNAMICS DECISION SYSTEMS',
            'GENERAL DYNAMICS C4SYSTEMS',

         ],

         'L3 COMMUNICATIONS' => [

            'NET-L3COM',
            'L3 COMMUNICATIONS ESS',
            'L3 COMMUNICATIONS (ELECTRODYNAMICS)',
            'L3 ELECTRONIC SYSYTEM SERVICES',
            'L3 COMMUNICATIONS SYSTEMS EAST',
            'L3COMMUNICATIONS',
            'L3 COMMUNICATIONS EO/IR',
            'L3 COMMUNICATIONS CORPORATION GCS DIVISION',
            'L3 COMMUNICATION LINK',
            'L3COMMUNICATIONS-AVIONICS SYSTEMS',
            'L3 COMMUNICATIONS CORPORATION',
            'L3 COMMUNICATIONS SPAR AEROSPACE',
            'L3 COMMUNICATIONS',
            'L3 APPLIED TECHNOLOGIES',
            'L3 TECHNOLOGIES',

         ],

         'SIKORSKY AIRCRAFT CORPORATION' => [
            'SIKORSKY AIRCRAFT CORPORATION',
            'SIKORSKY INTERNATIONAL OPERATIONS',
         ],

         'SNC-LAVALIN' => [

            'SNC-LAVALIN (MONTREAL)',
            'SNC-LAVALIN GEM ONTARIO',
            'SNC-LAVALIN ARCHITECTS AND',
            'SNC-LAVALIN ENVIRONMENT (HALIFAX)',
            'SNC-LAVALIN GRANDS PROJECTS',
            'SNC-LAVALIN DEFENCE PROGRAMS',
            'SNC-LAVALIN ENGINEERS AND CONSTRUCTORS',
            'SNC-LAVALIN CONSTRUCTION AECON JOINT V',
            'SNC-LAVALIN',
            'SNC-LAVALIN (WINNIPEG)',
            '"SNC-LAVALIN"',
            'SNC-LAVALIN ENVIRONMENT (VICTORIA)',
            'SNC-LAVALIN ENGINEERS & CONSTRUCTORS',
            'SNC-LAVALIN(HALIFAX)',
            'SNC-LAVALIN PROFAC',
            'SNC-LAVALIN PROFAC PROJECT MANAGEMENT UNIT',
            'SNC-LAVALINPROFAC',
            'SNC-LAVALIN O ET M',
            'SNC-LAVALIN PRO FAC',
            'SNC-LAVALIN OPERATIONS & MAINT',
            'SNC-LAVALIN GEM QUEBEC',
            'SNC-LAVALIN OPERATIONS &',
            'SNC-LAVALIN AIR LOGISTICS',
            'SNC-LAVALIN AGRO',
            'SNC-LAVALIN (TORONTO)',
            'SNC-LAVALIN PAE',
            'SNC-LAVALIN OPERATIONS & MAINTENANCE',
            'SNC-LAVALIN (BURNABY BC)',
            'SNC-LAVALIN ENVIRONMENT',
            'SNC-LAVALIN WIIBE',
            'SNC-LAVALIN INFRASTRUCTURE PVT',
            'SNC-LAVALIN (VICTORIA)',
            'SNC-LAVALIN (FREDERICTON)',
            'SNC-LAVALIN O & M',
            'SNC-LAVALIN (HALIFAX)',
            'SNC-LAVALIN O/A BAE NEWPLAN GROUP',
            'SNC-LAVALIN O&M',
            'ENVIRONMENT & WATER SNC-LAVALIN',
            'SNC-LAVALIN (OTTAWA)',
            'SNC-LAVALIN OPERATIONS',
            'SNC-LAVALIN OPERATIONS &; MAINTENANCE',
            'SNC-LAVALIN GRANDS PROJETS',
            'SNC-LAVALIN ENVIRONMENT DIVISION',
            'NISHI-KHON/SNC-LAVALIN LIMITED',
            'SNC-LAVALIN (EDMONTON)',
            'SNC-LAVALIN-',
            'SNC-LAVALIN PROFAC  869397091PG0006',
            'SNC-LAVALIN (LEVIS QC)',
            'SNC-LAVALIN  ENGINEERS & CONSTRUCTORS',
            'SNC-LAVALIN GEM QUA?BEC',
            'SNC-LAVALIN ENVIRONNEMENT',

         ],

         'KELOWNA FLIGHTCRAFT' => [
            'KELOWNA FLIGHTCRAFT AIR CHARTER',
            'KELOWNA FLIGHTCRAFT LIMITED',
         ],

         'GLAXOSMITHKLINE' => [

            'GLAXOSMITHKLINE',
            'GLAXOSMITHKLINE CONSUMER HEALTHCARE',
            'GLAXOSMITHKLINE CONSUMER',

         ],

         'LOCKHEED MARTIN' => [
            'LOCKHEED MARTIN GLOBAL',
            'LOCKHEED MARTIN SPACE OPERATION',
            'LOCKHEED MARTIN NAVAL ELECTRONICS & SURVEILLANCE SYSTEMS',
            'LOCKHEED MARTIN SERVICES',
            'LOCKHEED MARTIN AIRCRAFT & LOGISTICS CENTERS',
            'LOCKHEED MARTIN AERONAUTICAL SYSTEMS CO',
            'LOCKHEED MARTIN AERONAUTICS SERVICES INTERNATIONAL',
            'LOCKHEED MARTIN CORPORATION TRANSP & SECURITY SOLUTIONS',
            'LOCKHEED MARTIN CORPORATION MARITIME SYSTEMS AND SENSORS',
            'LOCKHEED MARTIN INFORMATION SYSTEMS UK',
            'LOCKHEED MARTIN MARITIME SYSTEMS & SENSORS',
            'LOCKHEED MARTIN CANADA',
            'LOCKHEED MARTIN NESS-MARINE SYSTEMS',
            'LOCKHEED MARTIN OVERSEAS SERVICES CORPORATION',
            'LOCKHEED MARTIN CANADA CDL SYSTEMS',
            'LOCKHEED MARTIN AERONAUTICS COMPANY',
            'LOCKHEED MARTIN OVERSEAS CORPORATION',
            'LOCKHEED MARTIN',
            'LOCKHEED MARTIN AERONAUTICS GLOBAL SUPPLY CHAIN SERVICES',
            'LOCKHEED MARTIN MISSILES AND FIRE CONTROL',
            'LOCKHEED MARTIN SIPPICAN',
            'LOCKHEED MARTIN UK INTEGRATED SYSTEMS AND SOLUTIONS LIMITED',
            'LOCKHEED MARTIN AIRCRAFT & LOGISITICS CENTERS',
            'LOCKHEED MARTIN CORPORATION',

         ],

         'PCL CONSTRUCTORS' => [

            'PCL CONSTRUCTORS EASTERN (NEPEAN)',
            'PCL MAXAM',
            'PCL MAXIM A JOINT VENTURE',
            'PCL/ED A JOINT VENTURE',
            'PCL-MAXAM A JOINT VENTURE',
            'PCL CONSTRUCTION MANAGEMENT',
            'PCL CONSTRUCTORS CANADA (DARTMOUTH)',
            'PCL CONSTRUCTORS WESTCOAST',
            'PCL CONSTRUCTORS NORTH',
            'PCL CONSTRUCTORS CANADA',
            'PCL CONSTRUCTORS NORTHERN',
            'PCL MAXAM A JOINT VENTURE',
            'PCL CONSTRUCTION MANAGMENT',
            'PCL CONSTRUCTORS EASTERN QUEBEC',
            'NISHI-KHON/PCL CONSTRUCTORS LIMITED',
            'PCL CONSTRUCTORS EASTERN',

         ],

         // References:
         // https://globenewswire.com/news-release/2018/02/14/1348209/0/en/BGIS-to-acquire-a-large-portfolio-of-Carillion-facilities-management-contracts-in-the-United-Kingdom.html

         'BROOKFIELD ASSET MANAGEMENT' => [

            'BROOKFIELD PROPERTIES MANAGEMENT',
            'BROOKFIELD GLOBAL INTEGRATED SOLUTI',
            'BROOKFIELD GLOBAL INTEGRATED SOLUTIONS CANADA LP',
            'BROOKFIELD LEPAGE JOHNSON',
            'BROOKFIELD LEPAGE JOHNSON CONTROLS',
            'BROOKFIELD WELL SERVICES',
            'BROOKFIELD JOHNSON CONTROLS CANADA',
            'BROOKFIELD LEPAGE JOHNSON CONTROL (',
            'BROOKFIELD GLOBAL INTEGRATED',
            'BROOKFIELD PROPERTIES MANAGEMENT CORPORATION',
            'BROOKFIELD LEPAGE JOHNSON CONTROLS PROPERTY MANAGER VANCOUVER REGIONAL OFFICE',
            'BROOKFIELD PROPERTIES',
            'BROOKFIELD GLOBAL RELOCATION SERVICES',
            'BROOKFIELD JOHNSON CONTROLS',
            'BROOKFIELD OFFICE PROP MNGT LP',
            'BROOKFIELD GLOBAL INTEGRATED SOLUTIONS',
            'BROOKFIELD GLOBAL RELOCATION SERVIC',
            'BROOKFIELD GLOBAL RELOCATION',
            'BROOKFIELD GLOBAL INTEGRATED SOLUTIONS CANADA GP',
            'BROOKFIELD GLOBAL',
            'BROOKFIELD SOLUTIONS GLOBALES INTEGREES',
            'BROOKFIELD',
            'BROOKFIELD GLOBAL RELOCATION SERVICES LIMITED',
            'BROOKFIELD PROPERTIES (ET)',
            'BROOKFIELD PROPERTIES MANAGEMENT CO',
            'BROOKFIELD SOLUTIONS GLOBALES',
            'BROOKFIELD GLOBAL INTERGRATED SOLUT',
            'BROOKFIELD PROPERTIES (PI)',
            'BROOKFIELD GLOBAL RELOCATION SERVS(',
            'BROOKFIELD PROPERTIES (PI]',
            'BROOKFIELD PROPERTIES MGMT',
            'BROOKFIELD MGT SERV JOHNSON CONTROLS WO',
            'BROOKFIELD LEPAGE JOHNSON CONTROLS FACILITY',
            'BROOKFIELD OFFICE  PROP MNGT LP',
            'BROOKFIELD GLOBAL RELOCATION SERV',
            'BROOKFIELD PROPERTIES CORPORATION',

         ],

         'THALES' => [

            'THALES COMMUNICATIONS',
            'THALES DEFENCE & SECURITY',
            'THALES UNDERWATER SYSTEMS',
            'THALES E-SECURITY',
            'THALES RAYTHEON SYSTEMS',
            'THALES CANADA OPTRONICS DIVISION',
            'THALES CANADA NAVAL SERVICES BU',
            'THALES DEFENSE & SECURITY',
            'THALES NORWAY AS',
            'THALES TRAINING AND SIMULATION LIMITED',
            'THALES LASER SA',
            'THALES ALENIA SPACE ITALIA',
            'THALES OPTRONIQUE CANADA',
            'THALES CANADA LAND & JOINT SYSTEMS OPTRONICS BUSINESS UNIT',
            'THALES CANADA SYSTEM',
            'THALES CANADA',
            'THALES DEFENSR & SECURITY',
            'THALES AUSTRALIA',
            'THALES CANADA SYSTEMS DIVISION',
            'THALES DEFENCE DEUTSCHLAND GMBH',
            'THALES DEFENSE SECURITY',
            'THALES NAVAL SERVICES CANADA',
            'THALES CANADA NAVAL SERVICES DIVISION',
            '"THALES CANADA NAVAL SERVICES DIVISION                "',
            'THALES AVIONICS',
            'THALES ACOUSTICS',
            'THALES OPTRONIQUE SA',
            '"THALES CANADA SYSTEMS DIVISION                    "',
            'THALES OPTRONICS CANADA',
            'THALES COMMUNICATIONS AND SECURITY',
            'THALES',

         ],

         'COMPUTERSHARE INVESTOR SERVICES' => [
            'COMPUTERSHARE INVESTOR',
            'COMPUTERSHARE TRUST COMPANY OF',
            'COMPUTERSHARE',
            'COMPUTERSHARE INVESTOR SERVICES',
         ],

         'CANADIAN BANK NOTE COMPANY' => [
            'CANADIAN BANK NOTE COMPANY LIMITED',
            'CANADIAN BANK NOTE COMPANYLTD',
            'CANADIAN BANK NOTE COLTD',
            'CANADIAN BANK NOTE CO',
            'CANADIAN BANK NOTE COMPANY',
         ],

         'CALIAN' => [

            'CALIAN (CALIAN)',
            'CALIAN TECHNOLOGY SERVICES',
            'CALIAN LDT',
            'CALIAN C/R109952',
            'CALIAN TECHNOLOGIES',
            'SED SYSTEMS A DIVISION OF CALIAN',
            'CALIAN LIMITES',
            'CALIAN',
            '** CALIAN',
            'CALIAN DOMINKNOW IN JOINT VENTURE',
            'CALIAN INSTRUX MEDIA CORP',
            'CALIAN COMMUNICATIONS SYSTEMS',
            'CALIAN LIMITED',
            'CALIAN SERVICES DOWNTOWN OFFICE',
            'CALIAN HUMAN RESOURCES',
            'CALIAN COMPUTING',
            'CALIAN JV INSTRUX MEDIA CORP',
            'CALIAN TEMP HELP',
            'CALIAN THS',
            'CALIAN OP THS DIVISION',
            'CALIAN TECHNOLOGY',
            'CALIAN TEMPORARY HELP SERVICES',
            'CALIAN TECH',

         ],

         'SKYLINK AVIATION' => [
            'SKYLINK AVIATION',
            'SKYLINK AVIATION & AIR CHARTER SERVICES',
            'SKYLINK',
            'SKYLINK PAE',
            'SKYLINK AVIAITON',
         ],

         'ELLISDON CORPORATION' => [
            'ELLISDON CORPORATION (OTTAWA)',
            'ELLISDON CORPORATION (HALIFAX)',
            'ELLISDON CORPORATION',
            'ELLISDON CONSTRUCTION SERVICES',
         ],

         'QUANTUM MANAGEMENT SERVICES' => [
            'LES SERVICES DE GESTION QUANTUM',
            'LES SERVICES DE GESTION QUANTUM LTA?(C)E',
            'LES SERVICES DE GESTION QUANTUM LTEE',
            'QUANTUM',
            'QUANTUM DENTAL TECHNOLOGIES',
            'QUANTUM HR',
            'QUANTUM INFORMATION RESOURCES',
            'QUANTUM MANAGEMENT',
            'QUANTUM MANAGEMENT SERV',
            'QUANTUM MANAGEMENT SERVICES',
            'QUANTUM MANAGEMENT SERVICES LES SERVIC',
            'QUANTUM MANAGEMENT SERVICES LES SERVICES DE GESTION QUANTUM LTA(C)E',
            'QUANTUM MANAGEMENT SERVICES LES SERVICES DE GESTION QUANTUM LTEE',
            'QUANTUM MANAGEMENT SERVICES LIMITED',
            'QUANTUM MANAGEMENT SERVICES LT',
            'QUANTUM MANAGEMENT SERVICES SERVICES DAIDE TEMPORAIRE',
            'QUANTUM MANAGEMENT SERVLTD',
            'QUANTUM MANAGEMENT SRV',
            'QUANTUM MANAGEMENT SYSTEMS',
            'QUANTUM MGMT SERVICES',
            'QUANTUM MGT SERVICES',
            'QUANTUM MNGMT',
            'QUANTUM TECHNOLOGY RECRUITING',
            'QUANTUME MANAGEMENT SERVICES LIMITED',
            'SERV GESTION QUANTUM LTEE',
            'SERVICES DE GESTION QUANTUM LTEE',
            'SERVICES GESTION QUANTUM LTEE',
         ],

         'MTS ALLSTREAM' => [
            'MTS COMMUNICATIONS',
            'MTS TESTING SYSTEMS (CANADA)',
            'MTSE',
            'MTS SYSTEMS CORP C/O INTERTECHNOLOGY',
            'MTS',
            'MTS ALLSTEAM',
            'MTS SYSTEM CORPORATION',
            'ALLSTREAM IT SERVICES (A DIVISION OF MTS ALLSTREAM)',
            'MTS SYSTEMS CORP',
            'MTS TESTING SYSTEMS CANADA',
            'MTS (ALLSTREAM)',
            'MTS SYSTEMS CORPORATION',
            'MTS ALLSTREAM WINNIPEG',
            'MTS ALLSTREAM',
            'MTS ALLSTREAM (FORMERLY QUNARA)',
            'MTS ADVANCED',
            'MTS MEDIA',
            'ALLSTREAM CORP',
            'ALLSTREAM CORPORATION',
            'MTS (ALLSTREAM)',
            'MTS ALLSTREAM',
            'ALLSTREAM',
            'MTS ALLSTREAM (FORMERLY QUNARA)',
            'ALLSTREAM (FORMERLY QUNARA)',
            'ALLSTREAM IT SERVICES ALLSTREAM CORP',
            'MTS ALLSTREAM WINNIPEG',
            'ALLSTREAM IT SERVICES',
            'ALLSTREAM IT SERVICES (A DIVISION OF MTS ALLSTREAM)',

         ],

         // REF:
         // https://www.newswire.ca/news-releases/canadian-submarine-management-group-csmg-inc-changes-name-to-babcock-canada-inc-509144461.html
         'BABCOCK CANADA' => [
            'BABCOCK INTEGRATED TECHNOLOGY LIMITED',
            'BABCOCK INTERNATIONAL GROUP MARINE AND TECHNOLOGY DIVISION',
            'BABCOCK INTEGRATED TECHNOLOGY',
            'BABCOCK CANADA',
            'BABCOCK INTEGRATED TECHNOLOGY CANADA',
            'CSMG',
         ],

         'NORTHERN MICRO' => [
            'EMC/ NORTHERN MICRO',
            'DONNA CONA C/O NORTHERN MICRO',
            'NORTHERN MICRO O/A  NORTHERN MICRO',
            'SYSTEMS INTEGRATION NORTHERN MICRO/DONNA CONA',
            'NORTHERN MICRO (CARE OF XEROX)',
            'DONNA CONA RESELLER: NORTHERN MICRO',
            'NORTHERN MICRO QUEBEC',
            'EMC/NORTHERN MICRO',
            'NORTHERN MICRO-',
            'NORTHERN  MICRO O/A NORTHERN MICRO',
            'NORTHERN MICRO',
            'NORTHERN MICRO O/A NORTHERN MICRO',
         ],
         'POMERLEAU' => [
            'POMERLEAU',
            'POMERLEAU (DARMOUTH)',
            'POMERLEAU (MONTRA(C)AL)',
            'POMERLEAU (BEDFORD)',
            'POMERLEAU (QUA(C)BEC)',
         ],
         'IMP GROUP' => [
            'IMP GROUP AEROSPACE DIVISION',
            'IMP SOLUTIONS C/O IMP GROUP',
            'IMP GROUP LIMITED IMP SOLUTIONS',
            'IMP GROUP',
            'IMP GROUP INDUSTRAIL MARINE PRODUCTS DIVISION',
            'IMP GROUP IMP SOLUTIONS',
            'IMP GROUP/IMP SOLUTIONS',
            'IMP GROUP LIMITED/OAK ISLAND INN',
            'IMP GROUP LIMITED',
            'IMP GROUP SOLUTIONS',
         ],
         'VERITAAQ TECHNOLOGY HOUSE' => [
            'VERITAAQ IT CONSULTING',
            'VERITAAQ TECHNOLOGY HOUSE',
            'VERITAAQ TECHNOLOGY HOUSING',
            'VERITAAQ TECHNOLOG HOUSE',
            'VERITAAQ TECHNOLOGY HOUSE OTTAWA',
            'VERITAAQ TECHNOLOGY HOUSE I',
            'VERITAAQ',
            'VERITAAQ TECHNOLOGY',
         ],
         'THE BOEING COMPANY' => [
            'THE BOEING COMPANY',
            'BOEING CANADA OPERATIONS- AEROINFO SYSTEMS & ACF ASSOCIATES',
            'MCDONNELL DOUGLAS CORPORATION A WHOLLY-OWNED SUBSIDIARY OF THE BOEING COMPANY',
            'BOEING AIRCRAFT COMPANY',
            'MCDONNELL DOUGLAS CORPORATION A WHOLLY-OWNED SUBSIDIARY OF THE BOEING',
         ],
         'FORD MOTOR COMPAMY' => [
            'FORD MOTOR COMPANY OF CANADA LIMITED/FORD DU CANADA LIMITEE',
            'FORD MOTOR COMPAMY',
            'FORD MOTORS',
            'FORD MOTOR COMPANY',
            'FORD MOTOR COMPANY OF CANADA LIMITED/FORD D',
            'FORD MOTOR COMPANY OF CANADA LIMITED',
            'FORD MOTOR COMPANY OF CANADA LIMITE',
            'FORD MOTOR COMPNAY OF CANADA',
            'FORD MOTOR COMPANY OF CANADS LIMITED',
            'FORD MOTOR COMPAGNY OF CANADA',
            'FORD MOTOR COMPANY OF CANADA 892183476PG0001',
            'FORD MOTOR CO OF CANADA',
            'FORD MOTOR COMPANY OF CA LIMITED',
            'FORD MOTOR COMPANY OF CANADA',
            'FORD MOTOR COMP OF CANADA',
            'FORD MOTOR COMPANY OF CANADA-',
            'FORD MOTOR CONPANY OF CANADA',
            'FORD MOTOR COMPANY OF CAN',
            'FORD MOTOR',
            'FORD MOTOR CO',
            'FORD MOTOR COMPANY OF CANADA LIMITEDFORD DU CANADA LIMITEE',
            'FORD MOTOR COMPANY OF CANADA ATTN: JACKIE PAYROLL',
            'FORD DU CANADA LIMITA?E',
            'FORD DU CANADA LIMITEE'
         ],
         'NISHA TECHONOLOGIES' => [
            'Nisha',
            'NISHA    Technologie',
            'NISHA TECHNOLOGIE INC.',
            'Nisha Technologies',
            'NISHA TECHNOLOGIES INC',
            'NISHA TECHNOLOGIES INC.',
            'NISHA TECHONOLOGIES',
            'NISHA-TECHNOLOGIES',
            'NISHA TECHONOLIGIES',
            'NISHA TECHNOLOGIES',
            'NISHATECH',
            'NISHA TECHNOLOGIESI',
            'NISHA TECNOLOGIES',
            'NISHA TECH',
            'CONTRACT COMMUNITY NISHA TECHNOLOGIES',
            'NISHA TECHNOLGIES',
            'NISHATECHNOLOGIES',
            'NISHA TECHNOLOGY',
            'THE NISHA GROUP',
            'NISHA TECHNOLOGIESINC',
            'NISHA TECHNOLOGIES CONTRACT',
            'NISHA TECHONOLOGIE',
            'CONTRACT COMMUNITY/NISHA TECHNOLOGIES IN JOINT-VENTURE',
            'NISHA TECHNOLOLIES',
            'NISHA TECHNOLOIES',
            'NISHA TECHNOLOGIES-',
            'NISHA TECHONOLGIES',
            'NISHA TECHOLOGIES',
         ],
         'CAE' => [
            'CAE FLIGHTSCAPE INC',
            'CAE INC',
            'CAE Simuflite Inc.',
            'CAE AIRCREW TRAINING SERVICES PLC',
            'CAE SAFETY CONSULTANTS',
            'CAE',
            'CAE MILITARY AVIATION TRAINING',
            'CAE PROFESSIONAL SERVICES (CANADA)',
            'CAE PROFESSIONAL SERVICES  ( CANADA',
         ],
         'SANOFI PASTEUR' => [
            'SANOFI PASTEUR',
            'SANOFI PASTEUR LIMITED',
            'SANOFI PASTEUR LIMITED/SANOFI PASTE',
            'SANOFI PASTEUR LIMITED/SANOFI PASTEUR LIMITE',
            'SANOFI PASTEUR SANOFI PASTEUR',
            'SANOFI PATERU LIMITED SANOFI PASTEUR LIMITEE',
         ],
         'SUN LIFE ASSURANCE COMPANY' => [
            '200 GRAHAM AND SUN LIFE ASSURANCE',
            'SUN LIFE ASSURANCE COMPANY',
            'SUN LIFE ASSURANCE COMPANY OF',
            'SUN LIFE ASSURANCE COMPANY OF CANAD',
            'SUN LIFE ASSURANCE COMPANY OF CANADA',
            'SUN LIFE ASSURANCE CO OF C',
         ],
         'UNISYS CANADA' => [
            'UNISYS',
            'UNISYS CANADA',
            'UNISYS CANADA (OTTAWA)',
         ],
         'MAPLE REINDERS CONSTRUCTORS' => [
            'MAPLE REINDERS CONSTRUCTORS',
            'MAPLE REINDERS',
         ],
         'SAP' => [
            'SAP AMERICA',
            'SAP CANADA',
            'SAP CANADA*****VOIR 2001324****',
            'SAP',
            'SAP 45 OCONNOR SUITE 600 OTTAWA ON K1P 1A4',
         ],
         'TELESAT' => [
            'TELESAT',
            'TELESAT CANADA',
         ],
         'UNITED STATES DEPARTMENT OF THE ARMY' => [
            'UNITED STATES DEPARTMENT OF THE ARMY (USASAC)',
            'UNITED STATES DEPARTMENT OF THE ARMY (TRADOC)',
            'UNITED STATES DEPARTMENT OF THE ARMY',
         ],
         'UNITED STATES DEPARTMENT OF THE NAVY' => [
            'UNITED STATES DEPARTMENT OF THE NAVY',
            'UNITED STATES DEPARTMENT OF THE NAVY (MISC)',
            'UNITED STATES DEPARTMENT OF THE NAVY (NAVAIR)',
            'UNITED STATES DEPARTMENT OF THE NAVY (NAVICP)',
            'UNITED STATES DEPARTMENT OF THE NAVY (NAVSEA)',
            'UNITED STATES DEPARTMENT OF THE NAVY (NETSAFA)',
            'UNITED STATES DEPARTMENT OF THE NAVY (SPAWAR)',
            'UNITED STATES NAVY',
            'US NAVY',
            'US NAVY SUPPORT FACILITY',
            'DEPT OF THE NAVY NAVAL FACILITY ENGINEERING COMMAND',
         ],
         'UNITED STATES DEPARTMENT OF THE AIR FORCE' => [
            'UNITED STATES AIR FORCE',
            'UNITED STATES DEPARTEMENT OF THE AIR FORCE (AFSAC)',
            'UNITED STATES DEPARTEMENT OF THE AIR FORCES AFSAC',
            'UNITED STATES DEPARTMENT OF THE AIR FORCE',
            'UNITED STATES DEPARTMENT OF THE AIR FORCE (AFSAC)',
            'UNITED STATES DEPARTMENT OF THE AIR FORCE (AFSAT)',
            'UNITED STATES DEPARTMENT OF THE AIR FORCE (SAF/IA)',
         ],
         'IMPERIAL OIL' => [
            'ESSO IMPERIAL OIL',
            'ESSO IMPERIAL OIL LIMITED',
            'ESSO PETROLEUM CANADA IMPERIAL OIL',
            'EXXIONMOBIL AVIATION (IMPERIAL OIL)',
            'EXXONMOBIL AVIATION (AKA IMPERIAL OIL)',
            'EXXONMOBIL AVIATION (IMPERIAL OIL)',
            'EXXONMOBIL IMPERIAL OIL',
            'EXXONMOBIL/IMPERIAL OIL',
            'IMPERIAL',
            'IMPERIAL AVIATION',
            'IMPERIAL ESSO',
            'IMPERIAL ESSO OIL',
            'IMPERIAL OIIL',
            'IMPERIAL OIL',
            'IMPERIAL OIL A PARTNERSHIP OF IMPERIAL OIL',
            'IMPERIAL OIL COMMERCIAL',
            'IMPERIAL OIL ESSO',
            'IMPERIAL OIL ESSO (EXXONMOBIL AVIATION',
            'IMPERIAL OIL ESSO (EXXONMOBIL AVIATION)',
            'IMPERIAL OIL ESSO LT5D',
            'IMPERIAL OIL (EXXON)',
            'IMPERIAL OIL EXXONMOBIL',
            'IMPERIAL OIL  EXXONMOBIL',
            'IMPERIAL OIL/EXXONMOBIL',
            'IMPERIAL OIL/ EXXONMOBIL',
            'IMPERIAL OIL/EXXON MOBIL',
            '"IMPERIAL OIL EXXONMOBIL AVIATION"',
            'IMPERIAL OIL EXXONMOBIL AVIATION',
            'IMPERIAL OIL FUEL EX ENERGY',
            'IMPERIAL OIL LDT',
            'IMPERIAL OIL LIMITED',
            'IMPERIAL OIL LIMITED AND MCCOLL-FRONTENAC PETROLEUM',
            'IMPERIAL OIL LIMITED AND MCCOLL FRONTENAC PETROLEUM (NOCO FUELS CANADA LP)',
            'IMPERIAL OIL LIMITED AND MCCOLL FRONTENAC PETROLIUM (NOCO FUELS CANADA LP)',
            'IMPERIAL OIL LIMITEDIMPERIAL OIL LIMITED',
            'IMPERIAL OIL LIMITED MCCOLL-FRONTENAC PETROLEUM',
            'IMPERIAL OIL MACDOUGALL ENERGY',
            'IMPERIAL OIL PETROLEUM AND CHEMICALS DIVISION',
            'IMPERIAL OIL PORDUCTS AND CHEMICALS DIVISIONS',
            'IMPERIAL OIL PRODCUTS',
            'IMPERIAL OIL PRODLUCTS',
            'IMPERIAL OIL PRODUCT',
            'IMPERIAL OIL PRODUCTS',
            'IMPERIAL OIL PRODUCTS AD CHEMICALS DIVISION',
            'IMPERIAL OIL PRODUCTS AND CHEMICALS DIVISION',
            'IMPERIAL OIL PRODUCTS AND CHMICALS DIVISION',
            'IMPERIAL OIL PRODUCTS DIVISION',
            'IMPERIAL OIS',
            'IMPERIAL OIT',
            'IMPERIAL OIUL',
            'IMPERIAL OLI',
            'PETROLIERE IMPERIALE',
         ],
         'LOGISTIK UNICORP' => [
            'LOGISTIK',
            'LOGISTIK INICORP',
            'LOGISTIKS UNICORP',
            'LOGISTIK UNICORP',
            'LOGISTIK UNICORPS',
            'LOGISTIK UNICROP',
         ],
         'SEASPAN VICTORIA SHIPYARDS' => [
            'SEASPAN MARINE CORPORATION VICTORIA SHIPYARDS CO',
            'SEASPAN VICTORIA SHIPYARDS',
            'VICTORIA SHIPYARDS CO',
            'VICTORIA SHIPYARDS COMPANY LIMITED',
         ],
         'COMPUGEN' => [
            'COMPUGEN',
            'COMPUGEN HORIZON',
            'COMPUGEN-HORIZON',
            'COMPUGEN HORIZON DARTMOUTH NS',
            'COMPUGEN LOGISTICS',
            'COMPUGEN LOGISTICS LIMITED',
            'COMPUGEN SYSTEMES LTEE',
            'COMPUGEN SYSTEMS',
            'COMPUGEN SYSTEMS (ALBERTA)',
            'COMPUGEN SYSTEMS LIMITED',
            'COMPUGEN SYSTEMS (OTTAWA)',
            'COMPUGEN (VMWARE)',
         ],
         'XEROX' => [
            'FUJI XEROX (CHINA) CO SHANGHAI',
            'FUJI XEROX (HONG KONG) LIMITED',
            'FUJI XEROX SHANGHAI CO',
            'FUJI XEROX TOKYO (K',
            'IDS XEROX',
            'RANK-XEROX',
            'XEROX',
            'XEROX CA',
            'XEROX CANADA',
            'XEROX  CANADA',
            'XEROX CANADA-',
            'XEROX CANADA BC ACC',
            'XEROX CANADA C/O PRINTER PLUS',
            'XEROX CANADA (DARTMOUTH)',
            'XEROX CANADA DARTMOUTH NS',
            'XEROX CANADA LIMITED',
            'XEROX CANADA LIMITEE',
            'XEROX CANADA LTA(C)E',
            'XEROX CANADA LTA?E',
            'XEROX CANADA LTE',
            'XEROX CANADA LTEE',
            'XEROX CANADANA LTEE',
            'XEROX CANADA OTTAWA',
            'XEROX CANADA  OTTAWA',
            'XEROX CANADA RESELLER CAPITAL CAD',
            'XEROX CANADA (SAINT JOHN)',
            'XEROX CANADA (ST-JOHN)',
            'XEROX CANADA (TORONTO)',
            'XEROX CANADA(TORONTO)',
            'XEROX CANADA(WINNIPEG)',
            'XEROX (CIC)',
            'XEROX CORPORATION',
            'XEROX EASTERN REGION BUSINESS SOLUTIONS',
            'XEROXGRAPHIC DIGITAL SOLUTIONS',
            'XEROX (HONG KONG)',
            'XEROX QUALITY SERVICES',
            'XEROX RESEARCH CENTRE OF CANADA',
            'XEROX SHANGHAI',
         ],
         'COSSETTE COMMUNICATIONS' => [
            'COSSETTE',
            'COSSETTE ATLANTIC',
            'COSSETTE COMMUHICATIONS',
            'COSSETTE COMMUNICATION',
            'COSSETTE COMMUNICATION GROUP',
            'COSSETTE COMMUNICATION-MARKETING',
            'COSSETTE COMMUNICATIONS',
            'COSSETTE DIGITAL',
            'COSSETTE MEDIA',
            'COSSETTE MEDIA ATTN: AOR CANADA',
            'COSSETTE MEDIA COSSETTE',
            'COSSETTE MEDIA COSSETTE COMMUNI',
            'GROUPE COSSETTE COMMUNICATION',
         ],
         'RAYTHEON' => [
            'RAYTHEON',
            'RAYTHEON ANSCHA?TZ GMBH',
            'RAYTHEON CANADA',
            'RAYTHEON CANADA LIMITED',
            'RAYTHEON CANADA LIMITED/RAYTHEON CANADA LIMITA(C)E',
            'RAYTHEON CANADA LIMITED/RAYTHEON CANADA LIMITA?E',
            'RAYTHEON COMPANY',
            'RAYTHEON COMPANY NCS',
            'RAYTHEON CYBER PRODUCTS',
            'RAYTHEON CYBER PRODUCTS LLC',
            'RAYTHEON MISSILE SYSTEMS',
            'RAYTHEON SECURE INFORMATION SYSTEMS LLC',
            'RAYTHEONSIS',
            'RAYTHEON SIS',
            'RAYTHEON SOLIPSYS',
            'RAYTHEON SYSTEMS CANADA',
            'RAYTHEON SYSTEMS COMPANY',
            'RAYTHEON SYSTEMS COMPANY INTERNATIONAL OPERATIONS',
            'RAYTHEON SYSTEMS LIMITED',
            'RAYTHEON TRUSTED COMPUTER SOLUTIONS',
         ],
         'GENERAL MOTORS' => [
            'GENERAL MOTORS',
            'GENERAL MOTORS CANADA',
            'GENERAL MOTORS OF CA',
            'GENERAL MOTORS OF CANADA',
            'GENERAL MOTORS OF CANADA-',
            'GENERAL MOTORS OF CANADA COMPANY',
            'GENERAL MOTORS OF CANADA FLEET SALES DEPT',
            'GENERAL MOTORS OF CANADA LIMITED',
            'GENERAL MOTORS OF CANADA LIMITED 101980753PG001',
            'GENERAL MOTORS OF CANADA LTEE',
            'GM DEFENSE ( A DIVISION OF GENERAL MOTORS OF CANADA LIMITED )',
            'OSHAWA GENERAL MOTORS OF CANADA',
         ],
         'HOGG ROBINSON CANADA' => [
            'HOGG ROBINSON CANADA',
            'HOGG ROBINSON PLC',
         ],
         'MEDAVIE' => [
            'MEDAVIE',
            'MEDAVIE EMS',
            'MEDAVIE HEALTHED',
         ],
         'CORADIX TECHNOLOGY CONSULTING' => [
            'CORADIX',
            'CORADIX CONSULTING',
            'CORADIX CONSULTING TECHNOLOGY CONSULTING',
            'CORADIX TECHNOLOGIY CONSULTING',
            'CORADIX TECHNOLOGY',
            'CORADIX TECHNOLOGY CONS SERVICES',
            'CORADIX TECHNOLOGY CONSULING',
            'CORADIX TECHNOLOGY CONSULTANT',
            'CORADIX TECHNOLOGY CONSULTANTING',
            'CORADIX TECHNOLOGY CONSULTING',
            'CORADIX TECHNOLOGY CONSULTING LIMITED',
            'CORADIX TECHNOLOGY CONSULTING TECHNOLOGY CONSULTING',
            'CORADIX TECHNOLOGY HOUSE',
            'CORADIX TECHONOLOGY CONSULTING',
            'CORADIX TECHONOLY CONSULTING',
            'DALIAN AND CORADIX',
            'DALIAN ENTERPRISE & CORADIX',
            'DALIAN ENTERPRISES AND CORADIX',
            'DALIAN ENTERPRISES AND CORADIX TECHNOLOGIES CONSULTING',
            'DALIAN ENTERPRISES AND CORADIX TECHNOLOGIES CONSULTING (IN JOINT VENTURE)',
            'DALIAN ENTERPRISES AND CORADIX TECHNOLOGIES CONSULTING IN JOINT VENTURE',
            'DALIAN ENTERPRISES AND CORADIX TECHNOLOGY CONSULTING IN JOINT VENTURE',
            'DALIAN ENTERPRISES AND CORADIX TECHNOLOGY IN JOINT VENTURE',
            'TEAM DALIAN DALIAN ENTERPRISES AND CORADIX JV',
         ],
         'WEATHERHAVEN CANADA' => [
            'WEATHERHAVEN',
            'WEATHERHAVEN       000509',
            'WEATHERHAVEN            000509',
            'WEATHERHAVEN CANADA',
            'WEATHERHAVEN CANADA RESOUCES',
            'WEATHERHAVEN CANADA RESOURCES',
            'WEATHERHAVEN CANADA RESOURCESLTD',
            'WEATHERHAVEN GLOBAL RESOURCE',
            'WEATHERHAVEN GLOBAL RESOURCES',
            'WEATHERHAVENGLOBAL RESOURCES',
            'WEATHERHAVEN (REGISTERED PARTNERSHIP CARRYING ON BUSINESS IN THE CITY',
            'WEATHERHAVEN RESOURCES',
         ],
         'ITEX' => [
            'ITEX',
            'ITEX ENTERPRISE SOLUTIONS',
            'ITEX Entreprise Solutions',
            'ITEX INC',
            'ITEX INC.',
            'ITEX',
            'ITEX AND IDS SYSTEMS',
            'ITEX AND IDS SYSTEMS CONSULTANTS AS A CONTRACTUAL JOINT VENT',
            'ITEX AND JHT DEFENCE',
            'ITEX DBA TECHNOLOGY',
            'ITEX DBA TECHNOLOGY INTEGRATION GROUP',
            'ITEX ENERPRISE SOLUTIONS',
            'ITEX ENTERPRISE',
            'ITEX ENTERPRISES',
            'ITEX ENTERPRISE SERVICES',
            'ITEX ENTERPRISE SOLUTION',
            'ITEX ENTERPRISES SOLUTIONS',
            'ITEX SOLUTIONS',
            'ITEX TECHNOLOGY',
            'ITEX/TIG',
            'TIG ITEX',
         ],
         'DONNA CONA' => [
            'DONNA CONA',
            'DONNA CONA II',
         ],
         'EMS TECHNOLOGIES' => [
            'EMS TECHNOLOGIES CANADA',
            'EMS TECHNOLOGIES',
         ],
         'INMARSAT SOLUTIONS' => [
            'INMARSAT',
            'INMARSAT SOLUTIONS',
            'INMARSAT SOLUTIONS (CANADA)',
            'INMARSAT SOLUTIONS (CANADA)/',
         ],
         'WEIR CANADA' => [
            'WEIR CANADA',
            'WEIR MARINE ENGINEERING',
         ],
         'SI SYSTEMS' => [
            'SI SYSTEMS',
            'SI SYSTEMS C9565C',
            'SI SYSTEMS DANIELLE SILVERMAN',
            'SI SYSTEMS INTEGRATORS LLC',
            'SI SYSTEMS PARTNERSHIP',
            'SI SYSTEMS PARTNERSHIP C9565C',
            'SI SYSTEMS RAYMOND CHA(C)NIER',
            'TEAM SI SYSTEMS',
            'S I SYSTEMS',
            'S I SYSTEMS C9565C',
            'S I SYSTEMS PARTNERSHIP',
         ],
         'TPG TECHNOLOGY CONSULTANTS' => [
            'TEAM TPG',
            'THE POWELL GROUP TPG TECHNOLOGY',
            'THE POWELL GROUP TPG TECHNOLOGY CONSULTING',
            'TPG CONSULTING',
            'TPG TECHNOLOGIES',
            'TPG TECHNOLOGY',
            'TPG TECHNOLOGY CONSULTANTS',
            'TPG TECHNOLOGY CONSULTING',
            'TPG TECHNOLOGY CONSULTINGAMITA CORPCUESTA SYSTEMSTHE DEVO',
            'TPG TECHNOLOGY CONSULTING AND INROUND INNOVATIONS CJV',
            'TPG TECHNOLOGY CONSULTING L',
         ],
         'DELL COMPUTER CORPORATION' => [
            'DELL',
            'DELLCANADA',
            'DELL CANADA',
            'DELL CANADA A/S NISHA TECHNOLOGIES',
            'DELL CANADA MONTREAL',
            'DELL CANADA/OPENSTORAGE SOLUTIONS',
            'DELL CANADA RESELLER ITEX ENTERPRISE SOLUTION',
            'DELL CANADA RESELLER: NISHA TECHNOLOGIES',
            'DELL CDA',
            'DELL COMPUTER',
            'DELL COMPUTER CORP',
            'DELL COMPUTER CORP (CANADA)',
            'DELL COMPUTER CORP NORTH YORK',
            'DELL COMPUTER CORPORATION',
            'DELL COMPUTER CORPORATION CANADA',
            'DELL COMPUTER K)',
            'DELL COMPUTERS',
            'DELL COMPUTERS CANADA',
            'DELL DUCHARME (DR)',
            'DELL EMC',
            'DELL FINANCIAL SERVICES',
            'DELL FINANCIAL SERVICES CANADA',
            'DELL GLOBAL SOLUTIONS ARCHITECT',
            'DELL HALLE GMBH',
            'DELL LCANADA',
            'DELL MARKETING',
            'ZYCOM (AS RESELLER FOR DELL)',
            'NISHA TECHNOLOGIE/ DELL CANADA',
         ],
         'IT/NET CONSULTANTS' => [
            'IT/NET',
            'IT/NET CONSULTANT',
            'IT/NET CONSULTANTS',
            'IT/NET CONSULTANTS IN MANAGEMENT & TECHNOLOGY',
            'IT/NET OTTAWA',
            'IT/NET OTTAWA-',
            'IT/NET-OTTAWA',
            'IT/NET OTTAWA CONSULTANTS IN MANAGEMENT & TECHNOLOGY',
            'IT/NET-OTTAWA (ITNET)',
            'IT/NET-OTTAWA KPMG LLP IN JOINT VENTURE',
            'IT/NET OTTAWA O/A IT/NET',
            'IT/NET OTTAWA THERESA MACQUILKIN',
            'TEAM IT/NET',
         ],
         'VALCOM CONSULTING' => [
            'VALCOM',
            'VALCOM CONSULTING',
            'VALCOM CONSULTING CMPANY',
            'VALCOM CONSULTING COMPANY',
            'VALCOM CONSULTING GROOUP',
            'VALCOM CONSULTING GROUP',
            'VALCOM CONSULTING GROUP-',
            'VALCOM CONSULTING GROUP (OTTAWA)',
            'VALCOM CONSULTUING GROUP',
            'VALCOM LIMITED',
         ],
         'CA CANADA COMPANY' => [
            'CA CANADA COMPANY',
            'CA CANADA COMPANY (#CA#)',
            'CA TECHNOLOGIES',
         ],


    ];
}
